### ISSUE TITLE
Dial on demand does not trigger whith the "sync"-option

### ISSUE THREAD

**Issue by sthibaul** [ppp-project/ppp#187]
From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=75797

“
With the upstream "ppp-2.3.11", dial on demand does not trigger when
the "sync"-option is enabled.
[...]
The reason is that when demand reads the frames from the loopback,
in sync mode, it doesn't recognize any valid frame because these
frames don't start with PPP_FLAG (I don't know why).
”

In Debian we are carrying the attached patch 
[oedod.txt](https://github.com/paulusmack/ppp/files/5753990/oedod.txt)

but I don't know if this is still relevant

**Comment by paulusmack** [comment]
Hmmm, dial-on-demand was never tested with the sync option, and in fact I don't know what devices would use that option.

To be accepted, the patch would need a sign-off and a description that explained the changes in the patch - in particular, what the large lump of code added to demand_rexmit() is doing.

**Comment by sthibaul** [comment]
Yes, the patch seemed not that clear to me ("I don't know why" is not a good reason :) ), that's why I posted it here as an issue rather than a PR, so people can comment on this whether they need it.

**Comment by paulusmack** [comment]
Closing this based on lack of responses from people saying they need this.
