### ISSUE TITLE
Add a way to query for plugin directory

### ISSUE THREAD

**Issue by pacho2** [ppp-project/ppp#19]
As discussed at:
https://bugs.gentoo.org/show_bug.cgi?id=519986

NetworkManager needs to get ppp plugin dir configured at build time with --with-pppd-plugin-dir=$(ppp_version). I have checked various distributions (debian, opensuse, fedora, arch...) and every one has a different workaround for this (some specify only a version, other checks for plugin dir running "ls" to know the one existing at that time (!)...)

Maybe would be interesting to provide a way to check for plugin dir used by built ppp that could allow other software to rely on it for building in proper place

Thanks a lot

**Comment by vincele** [comment]
maybe `pkg-config` as in https://github.com/paulusmack/ppp/pull/47 could be used for that purpose.

**Comment by Neustradamus** [comment]
PR: https://github.com/ppp-project/ppp/pull/270
