### ISSUE TITLE
pppoe-discovery hardcodes eth0

### ISSUE THREAD

**Issue by yarda** [ppp-project/ppp#219]
I think it should take the first available interface by default.
```
pppoe-discovery.c:
...
fprintf(stderr, "   -I if_name     -- Specify interface (default eth0)\n");
```

**Comment by Neustradamus** [comment]
@yarda: This part is not solved?

**Comment by yarda** [comment]
It doesn't seem to be solved, the eth0 is still hard-coded:
https://github.com/ppp-project/ppp/blob/master/pppd/plugins/pppoe/pppoe-discovery.c#L730
It's debugging tool, but I think it should behave consistently with the other tools/commands. Auto-detection is nice to have.

**Comment by Neustradamus** [comment]
@paulusmack: What do you think?

**Comment by pali** [comment]
I planned to look at this issue after reviewing and merging pull request which refactor pppoe-discovery: https://github.com/ppp-project/ppp/pull/209

**Comment by Neustradamus** [comment]
@pali has done the new PR:
- https://github.com/ppp-project/ppp/pull/330

@yarda: What do you think?

**Comment by yarda** [comment]
> @pali has done the new PR:
> 
>     * [pppoe-discovery: Do not set eth0 as default interface and valide all cmdline options #330](https://github.com/ppp-project/ppp/pull/330)
> 
> 
> @yarda: What do you think?

LGTM, thanks.
