### ISSUE TITLE
EAP-TLS to expose hook to verify peername

### ISSUE THREAD

**Issue by enaess** [ppp-project/ppp#250]
You have to specify "remotename" which may not be initially known to the end-user. For example, the server name you connect to may be azure-gw-xyzxyz.<somedomain>.com, but the name of the server which performs the EAP authentication may be a server internal to the network you are accessing. Omitting the "remotename" will cause PPP client to terminate the connection.

I'd like for ppp when using EAP-TLS to expose a hook/function that a plug-in can help validate the remote name (or not). Similarly to exposing the parameters for TLS authentication when using OpenVPN. 

See the attached screenshot. 

![Screenshot from 2021-02-12 16-32-28](https://user-images.githubusercontent.com/1057596/107835894-f2e6fb80-6d4f-11eb-8983-cf3ca2f330c6.png)

**Comment by enaess** [comment]
@jjkeijser - Do yo have an opinion on this?

**Comment by Neustradamus** [comment]
To follow this ticket.

**Comment by jjkeijser** [comment]
I'm a bit confused here - this is already possible **without** a hook:
```
  remotename  </CN= part of server certificate>
```

which will connect to a server only if the server certificate name matches **exactly** what is specified in `remotename`.

Having said that, adding a hook/mechanism similar to what openvpn has is possible (e.g. wildcard matching) but I'd much rather implement something similar to what openvpn does (allow wildcards in `remotename` ) than add a hook to call some external code (**security risk!**)

**Comment by enaess** [comment]
@jjkeijser 

Yes, the base-case feature of "exact match" works out of the box for "remotename". 

This however, is a problem for the end user when he connects for the first time. The "remotename" can be something widely different from the SSTP server s/he connects to, which isn't known beforehand. Currently, the only way to infer this on the client side is by looking in the logs (not very user friendly). In addition, there might be a pool of RADIUS servers, each server with a different certificate / subject name.

The OpenVPN configuration allows for the following: 
* Don't verify name (default)
* Verify whole subject exactly
* Verify name exactly
* Verify name by prefix
* Verify subject partially (Legacy Mode, strongly discouraged)

While the administrator can provide the user this information when he configures it, I've found that when authenticating to a Azure Cloud, the authentication provider is a permutation of the gateway instance name (automatically generated?). Which is a real problem for the end user, though it should probably be best resolved with a suffix match.

The "remotename" for pppd has been traditionally used for looking up the secret in chap or pap password files. Applying matching here might be a bit problematic. While it may be a **security risk**, allowing a plug-in to perform the vendor specific validation avoids having patch-set to pppd from distributions floating around, or waiting for the next release cycle of pppd (which may be years from now). Also, in doing so, are we introducing new dependencies like libpcre (or gasp, glib) for regular expression parsing? 

The simplest may be to just allow this?

**Comment by enaess** [comment]
By the way, how are you testing the EAP-TLS feature of PPPD, i.e. what protocol are you using for front-end?

**Comment by jjkeijser** [comment]
here's the code snippet from OpenVPN 2.4.9 that does the x509 name matching as specified in the NetworkManager plugin:
```
 426     /* verify X509 name or username against --verify-x509-[user]name */
 427     if (opt->verify_x509_type != VERIFY_X509_NONE)
 428     {
 429         if ( (opt->verify_x509_type == VERIFY_X509_SUBJECT_DN
 430               && strcmp(opt->verify_x509_name, subject) == 0)
 431              || (opt->verify_x509_type == VERIFY_X509_SUBJECT_RDN
 432                  && strcmp(opt->verify_x509_name, common_name) == 0)
 433              || (opt->verify_x509_type == VERIFY_X509_SUBJECT_RDN_PREFIX
 434                  && strncmp(opt->verify_x509_name, common_name,
 435                             strlen(opt->verify_x509_name)) == 0) )
```

that is,  there is no real regexp machine done at all, just partial matching on a name. Adding this to eap-tls.c will be the most straightforward and will make it quite similar to OpenVPN.

As for adding a hook, that is easily doable as well, but there's the *client side* security risk of someone launching a rogue plugin to do name checking.  Therefore I am hesitant , although similar hooks already exist for the password prompts (see `pppd/plugins/passprompt.c`).   

As far as testing is concerned:   I normally test eap-tls using both a PPP-over-SSH connection as well as using PPTPD + PPTP . I use the PPTPD setup mostly to test it using Windows clients (XP+7+10 ).  I do not have any automated testing in place.

**Comment by enaess** [comment]
@jjkeijser 

I can live with the proposed feature parity of OpenVPN for this. I still would like to see a hook be exposed for this, and that there is an option to skip this verification if user so desire. 

May suggest, two patch sets for this? One that handles the check per above details, and a secondary one that exposes a hook? The idea is here is that the hook will be introduced if I can come up with a patch to sstp/network-manager-sstp to handle user-interaction? That way we don't leave "unused" hooks in the code.

**Comment by jjkeijser** [comment]
Ah, so now work from my side is expected ;) ?
Do not expect a patch any time soon, it might be quicker if you write an initial patch and I review it.

**Comment by enaess** [comment]
LOL

I need this, so I get to do it? I have no problem with that. More importantly, if there is a consensus of what needs to be done and how, then we avoid the argumentation after the work is done ;-)

**Comment by jjkeijser** [comment]
All I am saying is that if you would like me to write this patch then you will need to be a little patient - this is not a High Priority thing for me.  Perhaps I can whip up something tomorrow afternoon, but esp the git PR part is the part that I hate.

**Comment by paulusmack** [comment]
> All I am saying is that if you would like me to write this patch then you will need to be a little patient - this is not a High Priority thing for me. Perhaps I can whip up something tomorrow afternoon, but esp the git PR part is the part that I hate.

I really don't want to force anyone into the github way of doing things - I think it is less than ideal myself. I'm happy to take patches posted to linux-ppp@vger.kernel.org for instance.

**Comment by enaess** [comment]
I really don't mind to do the work, but was holding off to see if @jjkeijser would. I am making some changes to support this for network-manager-sstp and I have it mostly done.

If I don't see anything, I'll create a PR ...

**Comment by Neustradamus** [comment]
#261 has been merged, thanks @enaess, @paulusmack.

**Comment by enaess** [comment]
Thanks, but this change also introduced a new bug. See #268. Submitted a patch for that already. Closing this issue.
