### ISSUE TITLE
Way of printing option descriptions?

### ISSUE THREAD

**Issue by njh** [ppp-project/ppp#251]
The `option_t` structure has a [description](https://github.com/paulusmack/ppp/blob/master/pppd/pppd.h#L107) string defined. And most of the `option_t` structure do seem to define a description for each of the options.

For example:
```C
    { "ipv6cp-accept-remote", o_bool, &ipv6cp_allowoptions[0].accept_remote,
      "Accept peer's interface identifier for itself", 1 },
```

But I can't see any way of printing this out?
Is it a feature waiting to be implemented?

**Comment by Neustradamus** [comment]
@paulusmack: What do you think?

**Comment by paulusmack** [comment]
> But I can't see any way of printing this out?
> Is it a feature waiting to be implemented?

Looks like it is.  I added that back in 1998, so I don't remember exactly what I had in mind.

A variant of the dump or dryrun option to print the selected options could be useful. Or a "long help" option to print all the option names and their descriptions.

**Comment by enaess** [comment]
Just opened a pull request to fix this.

**Comment by Neustradamus** [comment]
@paulusmack: Here: https://github.com/ppp-project/ppp/pull/365.

**Comment by njh** [comment]
@enaess Amazing! Thank you!

**Comment by enaess** [comment]
@paulusmack this issue can now be closed
