### ISSUE TITLE
Don't replace /etc/resolv.conf (when usepeerdns is enabled) - or at least provide a way to not do this ...

### ISSUE THREAD

**Issue by enaess** [ppp-project/ppp#266]
This may be more a question than an actual issue. But I've been using the option 'userpeerdns' to make pppd in client mode request the ms-dns addresses from the server. However, during ipcp_up, it overwrites the /etc/resolv.conf file. In modern Linux systems (that used by Canonical / Ubuntu), systemd-resolved handles the /etc/resolv.conf for you. I'd like to still ask the peer for the dns settings, but avoid writing the /etc/resolv.conf

The reason for me asking for this is an issue when connecting to Azure's VNnetGateway and P2S (Point to Site) configurations will provide a DNS server. It doesn't seem to respond to queries I give it (source IP may be outside of the VNET's address space). The guys over at Microsoft intended for this to be configured as a "split-tunnel" and even if this dns server would respond to authorized names, replacing the /etc/resolv.conf seems a bit drastic, especially if there are more than 1 working name servers. Right now, if I don't disable DNS forwarding entirely, the system's connections are completely dorked when logged onto my Azure cloud.

Perhaps introducing another option of  dont-replace-resolv-conf (and leaving current behavior intact)?

**Comment by paulusmack** [comment]
I don't believe pppd itself writes /etc/resolv.conf; it writes /etc/ppp/resolv.conf. You may have an ip-up script that is copying /etc/ppp/resolv.conf over to /etc/resolv.conf.

**Comment by enaess** [comment]
Looks like debian provides a /etc/ppp/ip-up.d/usepeerdns script that does this, but doesn't add nm-sstp-service to the list of things to skip. I'll check with them.
