### ISSUE TITLE
EAP-TLS support broken when openssl built with "no-engine"

### ISSUE THREAD

**Issue by OllieGitHub** [ppp-project/ppp#272]
Commit https://github.com/ppp-project/ppp/commit/e87fe1bbd37a1486c5223f110e9ce3ef75971f93 assumes that openssl was not built with the "no-engine" flag.

If it was, the ENGINE_* defines are not compiled in due to OPENSSL_NO_ENGINE being defined (see https://github.com/openssl/openssl/blob/master/include/openssl/engine.h), resulting in compiler errors

This should either be fixed in https://github.com/ppp-project/ppp/blob/master/pppd/eap-tls.c  (something like https://github.com/libssh2/libssh2/commit/d071e0e07b2d7f7e9b98150dc11991d702f37291) or properly communicated as a requirement in version 2.4.9

**Comment by Neustradamus** [comment]
@jjkeijser: It is for you!

**Comment by jjkeijser** [comment]
Fixed in commit `165ac54`

**Comment by Neustradamus** [comment]
@jjkeijser: Thanks!
PR: https://github.com/ppp-project/ppp/pull/273

@OllieGitHub: Can you test?

@paulusmack: Can you look to merge it?

**Comment by OllieGitHub** [comment]
@Neustradamus 
I can only confirm that is now builds.

Unfortunately I don't have the time or resources to check the functionality of the feature itself if that's what you were asking

**Comment by Neustradamus** [comment]
@OllieGitHub: It has been merged, can you close it?
- https://github.com/ppp-project/ppp/pull/273

Thanks @jjkeijser and @paulusmack.
