### ISSUE TITLE
macos/darwin compile support

### ISSUE THREAD

**Issue by Matt2843** [ppp-project/ppp#274]
Would it be possible to add macos/darwin configure/make support :)?

**Comment by paulusmack** [comment]
Certainly, if someone is willing to step up to do the port initially and then commit to ongoing testing and bug fixing.

**Comment by enaess** [comment]
Last time I looked at re-compiling pppd for Mac/Darwin, the system is missing a bunch of header files and you need entitlements from Apple. IIRC, the version on Mac is pppd 2.4.2 and heavily modified by Apple.

**Comment by xosevp** [comment]
Apple's ppp is at: https://opensource.apple.com/tarballs/ppp/

**Comment by enaess** [comment]
Yes, they do publish the source code with changes made to it, but unless you have xcode and entitlements + extra headers from Apple, it won't compile. Again, I tried this years ago. Not sure if anything has changed since then. Anyone is welcome to give it shot and prove me wrong
