### ISSUE TITLE
Support RFC7512 format for specifying PKCS11 keys with EAP-TLS 

### ISSUE THREAD

**Issue by enaess** [ppp-project/ppp#275]
I am on Ubuntu 20.04, and I tried to use SoftHSM and OpenSC to use PKCS11 tokens with EAP-TLS. 

Relevant packages:
* OpenSC (apt-get install opensc)
* SoftHSM (apt-get install softhsm2)
* libp11 from OpenSC (apt-get install libengine-pkcs11-openssl1.1)

As of current, using pppd w/pkcs11 support uses the old notation of pkcs:<slot>:<id>. If your certificate is located in slot 0, and with an id of 04, you specify this using pkcs11:0:04 for certfile and keyfile parameters.

However, this notation is considered "deprecated" or "legacy" with the recent version of OpenSSL's engine provided by the OpenSC project (pkcs11.so). Going forward, pppd needs to pass the certfile / keyfile parameters directly to the engine (without stripping "pkcs11:" prefix, and then allow the user to specify the certificate / key using RFC7512 (The PKCS11 URI scheme).

Current documentation of examples leads the user to think the output of the p11tool which lists the PKCS11 URI be the value to pass as the cert/key parameters to pppd. This will currently not work.

**Comment by Neustradamus** [comment]
@enaess: This ticket can be closed no?
