### ISSUE TITLE
Provide a variable/field that lets a plugin poke at the EAP mechanism in use

### ISSUE THREAD

**Issue by enaess** [ppp-project/ppp#276]
It would be very helpful to understand which EAP method was selected for authentication. Right now, there isn't anyone on the client side (except for ea_using_eaptls)

The eap_auth.ea_type field is unused on client side, not set when using eap-tls:
https://github.com/ppp-project/ppp/blob/d706c95906d996534f13632a747af5dc617f306e/pppd/eap.h#L156

Someone please correct me here, but there isn't one a different mechanism we can use in place of.

**Comment by Neustradamus** [comment]
@paulusmack: What do you think?

**Comment by enaess** [comment]
While I think this could be useful,  I don't think I need this particular feature of the moment.
