### ISSUE TITLE
Acct-Session-Id Attribute with wrong ID

### ISSUE THREAD

**Issue by EasyNetDev** [ppp-project/ppp#286]
Hi,

Could you please take a look to pppd/plugins/radius/util.c at the char *rc_mksid (void) function? Seems that slprintf is not formating correctly the output:

Example:
```
14:12:42.933231 po2.11 Out IP (tos 0x0, ttl 64, id 30677, offset 0, flags [DF], proto UDP (17), length 166)
    10.190.0.1.58480 > 89.A.B.C.1813: RADIUS, length: 138
        Accounting-Request (4), id: 0x50, Authenticator: ea546bb330ddebb7d65d8d15e4ef0463
          Acct-Session-Id Attribute (44), length: 16, Value: %lX60cb2c01%hX
```

After changing the function to snprintf:
```
char *
rc_mksid (void)
{
  static char buf[32];
  static unsigned short int cnt = 0;
//  slprintf(buf, sizeof(buf), "%08lX%04X%02hX",
  snprintf(buf, sizeof(buf), "%08lX%04X%02hX",
           (unsigned long int) time (NULL),
           (unsigned int) getpid (),
           cnt & 0xFF);
  cnt++;
  return buf;
}
```

The Acct-Session-Id is correct:

```
14:13:47.252695 IP (tos 0x0, ttl 64, id 45707, offset 0, flags [DF], proto UDP (17), length 162)
    10.190.0.1.39749 > 89.A.B.C.1813: RADIUS, length: 134
        Accounting-Request (4), id: 0x53, Authenticator: 22e07bcb93004f3ef85b4b5e93791c7b
          Acct-Session-Id Attribute (44), length: 18, Value: 60CB2E2F2459F900
          User-Name Attribute (1), length: 12, Value: adrian.ban
```

I've found few times issues with "sl.." functions, issues that you can't find in standard "sn.." functions.

**Comment by Neustradamus** [comment]
@paulusmack: What do you think?

**Comment by jkroonza** [comment]
We also just bumped into this.  In this case snprintf will work just fine, slprintf has a few things like %I (IP address) which obviously glibc knows nothing about.

In this case slprintf doesn't support the l operator to X (or rather, when l is encountered, it only deals with d and u.  The more correct fix is probably to fix slprintf, but replacing with snprintf in this case is adequate.

**Comment by Neustradamus** [comment]
@paulusmack: What do you think?

**Comment by paulusmack** [comment]
This one could indeed be snprintf. I'll fix it.

**Comment by paulusmack** [comment]
I just pushed the fix.

**Comment by Neustradamus** [comment]
Here: https://github.com/ppp-project/ppp/commit/301230f8fde94b5b80e9dfba51816ede340e6b64

**Comment by jkroonza** [comment]
Confirmed working thank you.
