### ISSUE TITLE
how to  slove this error?

### ISSUE THREAD

**Issue by jamesarch** [ppp-project/ppp#292]
os: centos 7 
pppd version: 2.4.8
This kind of error is often seen in the kernel information. How to deal with these problems? I have tried to change to the 2.4.5 version of the official  repo and the latest 2.4.9 will still have this kind of error
`segfault at 0 ip 000055c705e51b60 sp 00007ffea40d4540 error 4 in pppd[55c705e22000+58000]`

**Comment by Neustradamus** [comment]
@paulusmack, @yarda: What do you think?

**Comment by yarda** [comment]
No idea, it doesn't seem to be RHEL version, because in RHEL-7 the latest version is ppp-2.4.5-34 (and I suppose it's the same in the CentOS). AFAIK there are no similar reports for the RHEL-7. I can't speak for the CentOS, because I am not CentOS maintainer.

Backtrace could help.

**Comment by paulusmack** [comment]
If you want to debug it, and you know how to trigger it, you could run gdb and attach to the pppd process, trigger the bug, and then use gdb commands (e.g. "bt") to find out where in the program it got the segfault and hopefully also why.

With just the information given here it's impossible to say what's happening or why.

**Comment by jamesarch** [comment]
> If you want to debug it, and you know how to trigger it, you could run gdb and attach to the pppd process, trigger the bug, and then use gdb commands (e.g. "bt") to find out where in the program it got the segfault and hopefully also why.
> 
> With just the information given here it's impossible to say what's happening or why.

ok thanks
