### ISSUE TITLE
Add pppd persistent option

### ISSUE THREAD

**Issue by c-po** [ppp-project/ppp#312]
When pppd on-demand-dialing is enabled, pppd will create the e.g. `pppoe0` interface in advance with will be dialed once traffic passes.

It would be nice to add a switch named `persistent` to pppd configuration so that the interface is always created in advance even if no traffic flows through it. Having this option will enable a user to

* Have Firewalling code assigned to the interface before it is dialed and not make use of ip-up scripts
* Install some MSS clamping to the interface even when it is not yet up
* Specify interface aliases

**Comment by Neustradamus** [comment]
@paulusmack, @enaess: What do you think?

**Comment by c-po** [comment]
Hi @enaess,

this is the way how I am operating pppd right now (calling an ip-up helper script). It might be just a simply "my problem - not a common one" but my usecase is the following:

As beeing a maintainer of [VyOS](https://github.com/vyos) I wrote a simple Python library which abstracts all types of network interfaces with a common API for managing IP addresses, DHCP, ARP, prefix delegation what so ever. This library likes it that an interface is known in advance. I added a workaround to call the library from such a ip-up script but it simply feels "wrong" - again could be as simple as "my problem" ;).

Thinking of pppd in general I see two ways it behaves - if demand dialing is enabled, the ppp interface is created in advance, but if I do not use on-demand dialing it is not - this simply feels odd that it behaves in two different ways and I have no way of influencing this behavior.

On the other hand - is there a "downside" of making every ppp interface instance "on-demand dialing" with an infinite timeout?

**Comment by enaess** [comment]
I do remember having added on-demand option on the WatchGuard firewalls with PPPoE around 2006/07. You do describe a common problem for firewall vendors out there, and I am sure it would be nice to make it behave better. The -I pppoe+ was one that I recall using. I would have to look into it to tell if this would be even possible with how pppd is currently coded up, chances for regression, and a bunch of testing. I think Paul would be happy to accept well tested patches / PR on GitHub if you have one.

**Comment by paulusmack** [comment]
From pppd's perspective, it always creates the interface immediately (well, within a relatively short time) when pppd is started.

It sounds like you want to have a way to start pppd and have the interface created, but then have pppd hang around doing nothing until something triggers it to bring up the link. What is that something? How does pppd know when to bring up the link?

Or do you mean that something else creates the interface, then pppd gets started when we want the link to be established, and pppd takes over that existing interface? I don't think there is a way to get the kernel to turn some existing interface into a ppp interface, so that would not work.

Finally, if we call the option "persistent" then that is going to confuse users because there is already a "persist" option, and people will get confused about the difference between "persist" and "persistent", and which is which. We would have to come up with another name for the option.

**Comment by c-po** [comment]
Hi @paulusmack,

sorry for the late reply.

> It sounds like you want to have a way to start pppd and have the interface created, but then have pppd hang around doing nothing until something triggers it to bring up the link. What is that something? How does pppd know when to bring up the link?

Correct - that something could be a packet leaving that interface (like on-demand dialing which is already there)

> Or do you mean that something else creates the interface, then pppd gets started when we want the link to be established, and pppd takes over that existing interface? I don't think there is a way to get the kernel to turn some existing interface into a ppp interface, so that would not work.

This is what I wish I would be able to - regardless of the name of the options name - `persistent` might be a bad one indeed.

--
CP

**Comment by pali** [comment]
> Having this option will enable a user to
> 
> * Have Firewalling code assigned to the interface before it is dialed and not make use of ip-up scripts

You can already setup iptables for interface which does not exist or which is going to exist in future

> * Install some MSS clamping to the interface even when it is not yet up

This is also already possible, without any need for pppd modification. iptables's mss clamping can be setup also for interface which does not exist yet.

> * Specify interface aliases

What it is?

> Correct - that something could be a packet leaving that interface (like on-demand dialing which is already there)

So how it would differs from demand option?

> I don't think there is a way to get the kernel to turn some existing interface into a ppp interface, so that would not work.

Exactly there is no way for such thing in kernel. ppp kernel interface needs to be handled by pppd userspace daemon.

**Comment by c-po** [comment]
> What it is?

`ip link set dev ppp0 alias "Upstream Carrier 123"`

It is used e.g. on SNMP systems to get a more detailed description what that interface does. But as I read it everything can be achieved in one way or the other so this boils down to a "only me problem". Not an issue - just wanted to express my ideas/wished on pppd.

**Comment by pali** [comment]
Ok, so I think that you should be able to achieve that setup with existing pppd options (e.g. `demand`) and external scripts.
