### ISSUE TITLE
Restore DCO check

### ISSUE THREAD

**Issue by paulusmack** [ppp-project/ppp#322]
Somewhere in the process of setting things up to build and test the software, we lost the DCO check (the check that each commit has a Signed-off-by: line). We need to get that back.

**Comment by Neustradamus** [comment]
@RICCIARDI-Adrien, @enaess: If you can look it ^^

**Comment by RICCIARDI-Adrien** [comment]
Hi @paulusmack, DCO check might have been lost during the repository organization migration. You can install this GitHub app https://github.com/apps/dco to enable DCO checking.

**Comment by Neustradamus** [comment]
I think that the page has been changed:
- https://github.com/probot/dco/blob/master/docs/required-statuses.md

**Comment by enaess** [comment]
I did see the DCO check flagged two of my changes recently and had a red X marked in front of it in the workflows. Seems like this has been fixed now, no?

**Comment by RICCIARDI-Adrien** [comment]
As said by @enaess, DCO check is working (see the following picture taken from a pull request), so this issue may be closed.
![Capture d’écran_2022-08-19_10-05-43](https://user-images.githubusercontent.com/4292857/185573865-b870c321-e253-4c08-9e21-5980b8107186.png)
