### ISSUE TITLE
lcp-echo-adaptive does not set the lcp_echos_pending back to 0

### ISSUE THREAD

**Issue by electrofloat** [ppp-project/ppp#323]
Even after I set the lcp-echo-adaptive option for pppd, I sometimes still have a disconnect when the line is saturated.
I'm still investigating the issue, but looking at the code I just noticed, that in `LcpSendEchoRequest` if the `lcp_echo_adaptive` is true and there were some traffic in since last time, the function returns without setting the `lcp_echos_pending` back to 0.

This has the side effect of for example if someone has lcp-echo-failure set to 5, and it already failed 4 times, but then there were traffic so lcp-echo-adaptive kicked in for hours, then only after 1 failure the connection will be terminated, instead of 5 failures.

**Comment by Neustradamus** [comment]
@paulusmack: Have you seen this ticket?

**Comment by Neustradamus** [comment]
@electrofloat: @paulusmack has done a PR:
- https://github.com/ppp-project/ppp/pull/376

What do you think?

**Comment by electrofloat** [comment]
> @electrofloat: @paulusmack has done a PR:
> 
>     * [pppd: Fix spurious LCP echo failures with lcp-echo-adaptive option #376](https://github.com/ppp-project/ppp/pull/376)
> 
> 
> What do you think?

Looks great, that will fix this issue.
