### ISSUE TITLE
Improving Buildroot CI build speed.

### ISSUE THREAD

**Issue by RICCIARDI-Adrien** [ppp-project/ppp#329]
Hi all,

I've an idea about improving greatly the Buildroot CI build speed. The idea is to use precompiled Buildroot images to rebuild only the PPP package.

I would like to store this precompiled Buildroot images in a separate repository of PPP GitHub organization (for instance `ppp-ci`), in the repository Releases section. Indeed, GitHub says officially that there is no size limits for releases (see https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#distributing-large-binaries). It seems also fairly easy to deal with the maximum file limit of 2GB in a release (each file can be up to 2GB, but the amount of files is unlimited).

I would have liked to do something similar with the GitHub cache action, but the total cache size per workflow is limited to 10GB, while a single Buildroot build is about 7.5GB. If the 10GB cache limit is reached, older caches are evicted, so caching would be totally useless in our case.
I already made a test to cache the Buildroot sources and all downloaded packages, but this saves only some minutes (see https://github.com/RICCIARDI-Adrien/ppp/commit/605326152ef05d87fc46a70c4638ae88d521843b and https://github.com/RICCIARDI-Adrien/ppp/actions/runs/1567367830).

Creating a dedicated repository for the CI prebuilt images would provide several benefits :
* The CI stuff is separated from the PPP source code.
* All the PPP-related dependencies remain on GitHub, there is no need to depend on another service like Google Drive or Dropbox.
* Forked repositories CI will automatically work without any change.
* PPP developers can easily use the Buildroot prebuild images for their developments, so they could rely on fast local builds during development.
* I'm planning to add a shell script in this repository to generate any Buildroot image with a single command, and this can also be useful to developers.

What do you think about that ?

**Comment by paulusmack** [comment]
This all sounds fine to me. What is the next step to implement this?

**Comment by RICCIARDI-Adrien** [comment]
Great !
I would need access to the `ppp-ci` repo, I need to be able to create a release on this repo (but the permissions required for that can be revoked later when it's working). As there will be a lot of data to upload to GitHub, I would prefer to do that on the final repo instead of a temporary one to avoid uploading everything twice.

**Comment by Neustradamus** [comment]
@paulusmack: Here, tag page: https://github.com/ppp-project/ppp/tags and click on "...", you can see to create a release.

**Comment by RICCIARDI-Adrien** [comment]
I don't need to access to the currently existing `ppp` repo, I need to access to the `ppp-ci` repo that does not exist yet (someone has to create it for me too).
I need to create releases in the `ppp-ci` repo to be able to upload Buildroot builds here.

**Comment by RICCIARDI-Adrien** [comment]
Hi @paulusmack, what license do you want to use for `ppp-ci` repository ? Would `MIT` license be fine ?

**Comment by RICCIARDI-Adrien** [comment]
The new Buildroot CI is merged.
