### ISSUE TITLE
Any technical limitation for MTU > 1500 bytes?

### ISSUE THREAD

**Issue by minhng99** [ppp-project/ppp#331]
I see that for some reason, `ppp` is hardcoded a limit for MTU/MRU at max 1500 here:
https://github.com/ppp-project/ppp/blob/master/include/net/ppp_defs.h#L55

Even if I specify the MTU/MRU number higher than 1500 then it will just jump back to 1500
I know that a standard PPPoE MTU is supposed to be 1492 to add space for the overheads, I tried to raise those numbers to work with 1600 bytes and it seems to work just fine (my BRAS supported it).

My question is that why can't we make those MTU MRU dynamically fit with whatever the lower layer support and not limit it down to 1500? I feel like there's a reason for that but the .h file didn't tell me what it is... I need a larger MTU to help with the fragmentation issue if the client is using 4in6/DSLite.

**Comment by pali** [comment]
Hello @minhng99!

`PPP_MTU` should be just default MTU value and you should be able to adjust it via command line options.

Ad PPPoE: pppd has pppoe plugin in pppd/plugins/pppoe/ directory and it negotiate MTU based on PPPoE PADO tag `TAG_PPP_MAX_PAYLOAD` and MTU of the local ethernet interface (and of course command line options). So if you have configured ethernet interface for larger MTU && your BRAS supports `TAG_PPP_MAX_PAYLOAD` && you specified command line for larger MTU then you should be able to negotiate also MTU of 1600 bytes. If it does not work then there can be a bug in pppd's plugin or pppd code. But I do not think that pppd is limited to 1500 bytes if HW and OS supports also larger values.

**Comment by minhng99** [comment]
Oh, I was using the commit https://github.com/ppp-project/ppp/commit/ad3937a0a38a696eb1a37dbf8f92e8e6072cdccb which is what OpenWrt 21.02 used with their default package build, is this version different in some way?

Because on stock OpenWrt, if I tried to raise the MTU MRU 1600 then it just dropped back to 1500 as reported by my Mikrotik BRAS server, after I've recompiled the same version (applied all the OpenWrt patches) and modified the `PPP_MTU` and `PPP_MRU` then it's works fine with MTU 1600

and yes, the lower layer network adapter supported it just fine, this was tested on the same hardware.

**Comment by pali** [comment]
Could you try to use official pppd and not OpenWRT's forked version? OpenWRT is heavily patching and hacking pppd, so it is possible that you have hit another OpenWRT bug in pppd...

**Comment by Neustradamus** [comment]
For information: ppp patches are here:
- https://github.com/openwrt/openwrt/tree/master/package/network/services/ppp/patches
- https://git.openwrt.org/openwrt/openwrt.git?p=openwrt%2Fopenwrt.git&a=search&h=HEAD&st=commit&s=ppp

**Comment by minhng99** [comment]
Maybe this patch is the cause of this issue?
https://github.com/openwrt/openwrt/blob/openwrt-21.02/package/network/services/ppp/patches/207-lcp_mtu_max.patch

I haven't got the time to try it yet, just guessing... there may be another week before I could try to build without the patches and test it.

**Comment by pali** [comment]
Sorry I do not know. I'm not going to spend time again with something broken in OpenWRT. My advice is to use official upstream version. And if you are using OpenWRT version then do not report bugs to upstream... instead report them to OpenWRT.

**Comment by minhng99** [comment]
Alright, thanks, looks like it might be a bug from OpenWrt then.

**Comment by Neustradamus** [comment]
@jow-, @hauke, @dedeckeh: Can you look this ticket?

Linked to:
- https://github.com/openwrt/openwrt/blob/master/package/network/services/ppp/patches/207-lcp_mtu_max.patch

Thanks in advance.

**Comment by Neustradamus** [comment]
@minhng99: Have you news from @openwrt team?

cc: @jow-, @hauke, @dedeckeh.

**Comment by minhng99** [comment]
No, I didn't actually test it yet, busy with some stuff... I only suspect that patch is the cause because it touched something related to MTU MRU max value

**Comment by jow-** [comment]
Can't really test due to a lack of a ppp link but from reading the patch and the original source I can't immediately see how the patch is related. `ao->mru` (a.k.a. `lcp_allowoptions[0].mru`) should be initialized to `MAXMRU` (16384) so it would not cap whatever value would be used otherwise.
