### ISSUE TITLE
auth.c:893: undefined reference to `crypt'

### ISSUE THREAD

**Issue by ptorrent** [ppp-project/ppp#333]
Hey there !

I'm not able to compile from source

```
./configure
make
```

auth.c:893: undefined reference to `crypt'

Is there a way to solve this issue ? 

Thanks a lot for your support !

**Comment by paulusmack** [comment]
We will need more information to be able to help you. Are you compiling a release, or if not, what is the git SHA1 id of the commit you are trying to build from?

What operating system and version are you using? Are you cross-compiling and if so for what architecture and OS?

If you are building from git commit ab4d4992050e (24 July 2021) or later, please attach the config.log that was produced by the ./configure step.

**Comment by Neustradamus** [comment]
@ptorrent: Have you seen the comment of @paulusmack?

**Comment by enaess** [comment]
At the moment, this should only happen if you try to compile without openssl. This means, if you didn't specify --without-openssl to configure, then you don't have the openssl headers installed. 

Glibc 2.27 removed the crypt / des functions, and we don't have a replacement for these. We'll have to find a replacement other than libcrypt (via glibc).

**Comment by thesamesam** [comment]
> At the moment, this should only happen if you try to compile without openssl. This means, if you didn't specify --without-openssl to configure, then you don't have the openssl headers installed.
> 
> Glibc 2.27 removed the crypt / des functions, and we don't have a replacement for these. We'll have to find a replacement other than libcrypt (via glibc).

glibc still provides `crypt(3)` but since 2.27, _glibc's implementation_ is deprecated and they allow disabling building them. It's expected that systems will then use another implementation like libxcrypt.

As long as we search for `-lcrypt` in the build system and use it appropriately, there's no issue. I say this having just done the big migration for my distro :)

**Comment by thesamesam** [comment]
I can reproduce _a_ failure, no idea if it's the same one, when I build with `./configure --without-openssl --disable-eaptls --disable-peap`:

```
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2  -Wl,-E    -o pppd pppd-auth.o pppd-ccp.o pppd-chap-md5.o pppd-chap-new.o pppd-demand.o pppd-eap.o pppd-ecp.o pppd-fsm.o pppd-ipcp.o pppd-lcp.o pppd-magic.o pppd-main.o pppd-options.o pppd-session.o pppd-tty.o pppd-upap.o pppd-utils.o pppd-sys-linux.o  pppd-chap_ms.o pppd-pppcrypt.o   pppd-mppe.o   pppd-ipv6cp.o pppd-eui64.o    -lcrypt   -lpcap -ldl -lpam -ldl libppp_crypt.la
libtool: link: gcc -g -O2 -Wl,-E -o pppd pppd-auth.o pppd-ccp.o pppd-chap-md5.o pppd-chap-new.o pppd-demand.o pppd-eap.o pppd-ecp.o pppd-fsm.o pppd-ipcp.o pppd-lcp.o pppd-magic.o pppd-main.o pppd-options.o pppd-session.o pppd-tty.o pppd-upap.o pppd-utils.o pppd-sys-linux.o pppd-chap_ms.o pppd-pppcrypt.o pppd-mppe.o pppd-ipv6cp.o pppd-eui64.o  -lcrypt -lpcap -lpam -ldl ./.libs/libppp_crypt.a
/usr/lib/gcc/x86_64-pc-linux-gnu/12.1.1/../../../../x86_64-pc-linux-gnu/bin/ld: pppd-pppcrypt.o: in function `DesSetkey':
/home/sam/git/ppp/pppd/pppcrypt.c:120: undefined reference to `setkey'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.1.1/../../../../x86_64-pc-linux-gnu/bin/ld: pppd-pppcrypt.o: in function `DesEncrypt':
/home/sam/git/ppp/pppd/pppcrypt.c:133: undefined reference to `encrypt'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.1.1/../../../../x86_64-pc-linux-gnu/bin/ld: pppd-pppcrypt.o: in function `DesDecrypt':
/home/sam/git/ppp/pppd/pppcrypt.c:147: undefined reference to `encrypt'
```

From `setkey(3)`:
```
       #define _XOPEN_SOURCE       /* See feature_test_macros(7) */
       #include <unistd.h>

       void encrypt(char block[64], int edflag);

       #define _XOPEN_SOURCE       /* See feature_test_macros(7) */
       #include <stdlib.h>

       void setkey(const char *key);
```

I think the issue is we're not defining `_XOPEN_SOURCE` early enough (it has to be at the point of first include because of include guards). But sadly, if I try setting it at the point of first inclusion of those headers, I get a bunch of conflicting definitions. :(

**Comment by Neustradamus** [comment]
@ptorrent, @thesamesam, @paulusmack: Have you seen the @enaess PR?
- https://github.com/ppp-project/ppp/pull/362
