### ISSUE TITLE
PPP sever dial up

### ISSUE THREAD

**Issue by Comely11** [ppp-project/ppp#336]

**Comment by Comely11** [comment]
After setting up the server script, I dialed with the command pppd /dev/ttys0 and found no feedback that the PPPD service did not seem to start properly.
`
this options.ttyS0 code：
115200
modem
auth
silent
nodetach
crtscts
asyncmp 0
passive
proxyarp
192.168.1.20:192.168.1.21
netmask 255.255.255.0
ms-dns 192.168.1.0
require-pap
`

**Comment by paulusmack** [comment]
What did you expect to happen, that didn't?

With the 'passive' and 'silent' options, pppd will just sit there waiting to receive something from the other end, without sending anything to initiate a connection.

You should have seen a 'pppd started' message logged in /var/log/messages or wherever your syslog service sends facility "daemon" messages to.

**Comment by Neustradamus** [comment]
@Comely11: Can you reply to @paulusmack more one year after?

**Comment by Comely11** [comment]
Sorry, I solved this problem a year ago and didn't notify you in time.

**Comment by Neustradamus** [comment]
@Comely11: How have you solved it?
And please close the ticket too.

**Comment by Neustradamus** [comment]
@Comely11: Thanks but how have you solved it?
