### ISSUE TITLE
Missing /var/lock directory

### ISSUE THREAD

**Issue by hellow554** [ppp-project/ppp#339]
I have a custom linux distribution built with yocto. On that, I use systemd.

systemd deprecated the /var/lock directory and doesn't create is per default anymore: https://github.com/systemd/systemd/issues/15668

I had a similar issue with a different program dt-utils from the barebox project, here's a little chat between me and a yocto maintainer: https://bugzilla.yoctoproject.org/show_bug.cgi?id=14186

dt-utils accepted a patch (not by me) that changed the lock directory: https://git.pengutronix.de/cgit/tools/dt-utils/commit/src/barebox-state.c?id=fd48fe4efb40f35b119958495d56b399bec73654

My question: would you think creating a lock directory `/run/ppp/` which contains the lock files would be feasible?

I my systemd environment I would use [tempfiles](https://www.man7.org/linux/man-pages/man8/systemd-tmpfiles.8.html) to generate that directory. I just the question, what people without systemd can do? Should there be a check if that directory exists and if not creating it?

I would try to submit a patch for this, if you like. I just want to hear your opinion

**Comment by paulusmack** [comment]
The lock directory location seems like something that should be configured via the configure script, i.e. perhaps you need to add a stanza to configure.ac. @enaess what do you think?

**Comment by enaess** [comment]
I think it should be doable. Generally, it probably should be tied to one of the already defined directory variables, e.g. localstatedir. 

Though, I do need to better understand the problem first before making any rush recommendation for which variable ...


https://www.gnu.org/software/autoconf/manual/autoconf-2.67/html_node/Installation-Directory-Variables.html

**Comment by hellow554** [comment]
I think [`runstatedir`](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html) is a very good candiate:

> The directory for installing data files which the programs modify while they run, that pertain to one specific machine, and **which need not persist longer than the execution of the program**

(emphasis mine)

**Comment by enaess** [comment]
Just to clarify the last comment there:

In autotools:
```
  --localstatedir=DIR     modifiable single-machine data [PREFIX/var]
  --runstatedir=DIR       modifiable per-process data [LOCALSTATEDIR/run]
```

The resulting location should be something along the lines of /usr/var/run unless the maintainer of the package overrides these. Typically, that would be done for a few variables, e.g. --prefix=/usr --sysconfdir=/etc --localstatedir=/var, then if the variable uses runstatedir, the resulting locations will be

* /etc/ppp/pppd.options
* /usr/sbin/pppd 
* /var/run/lock
* ...

Keying off the lock directory using runstatedir seems appropriate.

**Comment by enaess** [comment]
@paulusmack @hellow554 - PR#358 fixed his, please close this.

**Comment by hellow554** [comment]
Thanks @enaess for the awesome work.
You can use some of [the keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to close an issue automatically, when a PR is merged.
