### ISSUE TITLE
pppd 2.3.8 LTE connection problems

### ISSUE THREAD

**Issue by davbatt** [ppp-project/ppp#347]
Hello everyone,
I've an old device with ucLinux version 2.4.32-uc0 and pppd 2.3.8, that I normally use with an old GPRS radio, where I establish the PPP connection. 
I would like to connect it to a modern LTE radio, but during the authentication phase , LCP seems to return CONFACK, but the authentication fails and therefore IPCP does not start. 

The chap-secrets file is configured, in this way:
# User   Server   Password   Ip
""      *         ""         * 

Questions:
- Could it be CHAP code incompatibility and therefore pppd 2.3.8 is too old ?  
- Maybe the LTE network server uses MS-CHAP (server name "UMTS_CHAP_SRVR", I don't know...) ? 
- do you have any other ideas ?

I saw this in the list of changes in version ppp-2.4.2

What was new in ppp-2.4.2.
**************************
* The CHAP code has been rewritten.  Pppd now has support for MS-CHAP
  V1 and V2 authentication, both as server and client.  The new CHAP
  code is cleaner than the old code and avoids some copyright problems
  that existed in the old code.

For better understanding, I attach below the pppd launch options and debug printed in /var/log/messages.

Thank you for your help.
  
1- pppd options:
/bin/pppd /dev/modem modem nocrtscts debug 57600 lcp-echo-failure 3 lcp-echo-interval 60 defaultroute usepeerdns usehostname -detach noauth noipdefault connect '/bin/chat -v -f /etc/ppp/gprs-chat'

2- /var/log/messages:

<5>May 20 14:22:17 pppd[536]: pppd 2.3.8 started by (unknown), uid 0
<6>May 20 14:22:18 chat[537]: abort on (BUSY)
<6>May 20 14:22:18 chat[537]: abort on (NO CARRIER)
<6>May 20 14:22:18 chat[537]: abort on (VOICE)
<6>May 20 14:22:18 chat[537]: abort on (NO DIALTONE)
<6>May 20 14:22:18 chat[537]: abort on (NO DIAL TONE)
<6>May 20 14:22:18 chat[537]: abort on (NO ANSWER)
<6>May 20 14:22:18 chat[537]: abort on (DELAYED)
<6>May 20 14:22:18 chat[537]: timeout set to 10 seconds
<6>May 20 14:22:18 chat[537]: send (\dAT^M)
<6>May 20 14:22:19 chat[537]: expect (OK)
<6>May 20 14:22:19 chat[537]: AT^M^M
<6>May 20 14:22:19 chat[537]: OK
<6>May 20 14:22:19 chat[537]:  -- got it
<6>May 20 14:22:19 chat[537]: send (\dATZ^M)
<6>May 20 14:22:20 chat[537]: expect (OK)
<6>May 20 14:22:20 chat[537]: ^M
<6>May 20 14:22:20 chat[537]: ATZ^M^M
<6>May 20 14:22:20 chat[537]: OK
<6>May 20 14:22:20 chat[537]:  -- got it
<6>May 20 14:22:20 chat[537]: send (\dAT+CMEE=2^M)
<6>May 20 14:22:22 chat[537]: expect (OK)
<6>May 20 14:22:22 chat[537]: ^M
<6>May 20 14:22:22 chat[537]: AT+CMEE=2^M^M
<6>May 20 14:22:22 chat[537]: OK
<6>May 20 14:22:22 chat[537]:  -- got it
<6>May 20 14:22:22 chat[537]: send (\dAT+CGATT=0^M)
<6>May 20 14:22:23 chat[537]: expect (OK)
<6>May 20 14:22:23 chat[537]: ^M
<6>May 20 14:22:25 chat[537]: AT+CGATT=0^M^M
<6>May 20 14:22:25 chat[537]: OK
<6>May 20 14:22:25 chat[537]:  -- got it
<6>May 20 14:22:25 chat[537]: send (\dAT+CGDCONT=1^M)
<6>May 20 14:22:26 chat[537]: expect (OK)
<6>May 20 14:22:26 chat[537]: ^M
<6>May 20 14:22:27 chat[537]: AT+CGDCONT=1^M^M
<6>May 20 14:22:27 chat[537]: OK
<6>May 20 14:22:27 chat[537]:  -- got it
<6>May 20 14:22:27 chat[537]: send (\dAT+CREG?^M)
<6>May 20 14:22:28 chat[537]: expect (OK)
<6>May 20 14:22:28 chat[537]: ^M
<6>May 20 14:22:28 chat[537]: AT+CREG?^M^M
<6>May 20 14:22:28 chat[537]: +CREG: 0,1^M
<6>May 20 14:22:28 chat[537]: ^M
<6>May 20 14:22:28 chat[537]: OK
<6>May 20 14:22:28 chat[537]:  -- got it
<6>May 20 14:22:28 chat[537]: send (\dAT+CSQ^M)
<6>May 20 14:22:29 chat[537]: expect (OK)
<6>May 20 14:22:29 chat[537]: ^M
<6>May 20 14:22:29 chat[537]: AT+CSQ^M^M
<6>May 20 14:22:29 chat[537]: +CSQ: 23,0^M
<6>May 20 14:22:29 chat[537]: ^M
<6>May 20 14:22:29 chat[537]: OK
<6>May 20 14:22:29 chat[537]:  -- got it
<6>May 20 14:22:29 chat[537]: send (\dAT+COPS?^M)
<6>May 20 14:22:30 chat[537]: expect (OK)
<6>May 20 14:22:30 chat[537]: ^M
<6>May 20 14:22:30 chat[537]: AT+COPS?^M^M
<6>May 20 14:22:30 chat[537]: +COPS: 0,0,"WINDTRE",0^M
<6>May 20 14:22:30 chat[537]: ^M
<6>May 20 14:22:30 chat[537]: OK
<6>May 20 14:22:30 chat[537]:  -- got it
<6>May 20 14:22:30 chat[537]: send (\dAT+CGDCONT?^M)
<6>May 20 14:22:32 chat[537]: expect (OK)
<6>May 20 14:22:32 chat[537]: ^M
<6>May 20 14:22:32 chat[537]: AT+CGDCONT?^M^M
<6>May 20 14:22:32 chat[537]: +CGDCONT: 1,"IPV4V6","","",0,0,0,0^M
<6>May 20 14:22:32 chat[537]: +CGDCONT: 2,"IPV4V6","ims","",0,0,0,0^M
<6>May 20 14:22:32 chat[537]: +CGDCONT: 3,"IPV4V6","sos","",0,0,0,1^M
<6>May 20 14:22:32 chat[537]: ^M
<6>May 20 14:22:32 chat[537]: OK
<6>May 20 14:22:32 chat[537]:  -- got it
<6>May 20 14:22:32 chat[537]: send (\dAT+CGDCONT=1,"IP","myinternet.wind","0.0.0.0",0,0^M)
<6>May 20 14:22:34 chat[537]: expect (OK)
<6>May 20 14:22:34 chat[537]: ^M
<6>May 20 14:22:34 chat[537]: AT+CGDCONT=1,"IP","myinternet.wind","0.0.0.0",0,0^M^M
<6>May 20 14:22:34 chat[537]: OK
<6>May 20 14:22:34 chat[537]:  -- got it
<6>May 20 14:22:34 chat[537]: send (\dAT+CGACT=1,1^M)
<6>May 20 14:22:35 chat[537]: expect (OK)
<6>May 20 14:22:35 chat[537]: ^M
<6>May 20 14:22:36 chat[537]: AT+CGACT=1,1^M^M
<6>May 20 14:22:36 chat[537]: OK
<6>May 20 14:22:36 chat[537]:  -- got it
<6>May 20 14:22:36 chat[537]: send (\dAT+CGACT?^M)
<6>May 20 14:22:37 chat[537]: expect (OK)
<6>May 20 14:22:37 chat[537]: ^M
<6>May 20 14:22:37 chat[537]: AT+CGACT?^M^M
<6>May 20 14:22:37 chat[537]: +CGACT: 1,1^M
<6>May 20 14:22:37 chat[537]: +CGACT: 2,0^M
<6>May 20 14:22:37 chat[537]: +CGACT: 3,0^M
<6>May 20 14:22:37 chat[537]: ^M
<6>May 20 14:22:37 chat[537]: OK
<6>May 20 14:22:37 chat[537]:  -- got it
<6>May 20 14:22:37 chat[537]: send (\dAT+CGATT=1^M)
<6>May 20 14:22:39 chat[537]: expect (OK)
<6>May 20 14:22:39 chat[537]: ^M
<6>May 20 14:22:39 chat[537]: AT+CGATT=1^M^M
<6>May 20 14:22:39 chat[537]: OK
<6>May 20 14:22:39 chat[537]:  -- got it
<6>May 20 14:22:39 chat[537]: send (\dAT+CGATT?^M)
<6>May 20 14:22:40 chat[537]: expect (OK)
<6>May 20 14:22:40 chat[537]: ^M
<6>May 20 14:22:40 chat[537]: AT+CGATT?^M^M
<6>May 20 14:22:40 chat[537]: +CGATT: 1^M
<6>May 20 14:22:40 chat[537]: ^M
<6>May 20 14:22:40 chat[537]: OK
<6>May 20 14:22:40 chat[537]:  -- got it
<6>May 20 14:22:40 chat[537]: send (\dATDT*99***1#^M)
<6>May 20 14:22:41 chat[537]: expect (CONNECT)
<6>May 20 14:22:41 chat[537]: ^M
<6>May 20 14:22:41 chat[537]: ATDT*99***1#^M^M
<6>May 20 14:22:41 chat[537]: CONNECT
<6>May 20 14:22:41 chat[537]:  -- got it
<6>May 20 14:22:41 chat[537]: send (^M)
<6>May 20 14:22:41 pppd[536]: Serial connection established.
<7>May 20 14:22:41 pppd[536]: using channel 23
<6>May 20 14:22:41 pppd[536]: Using interface ppp0
<5>May 20 14:22:41 pppd[536]: pppd create pidfile /var/run/ppp0.pid
<5>May 20 14:22:41 pppd[536]: Connect: ppp0 <--> /dev/modem
<7>May 20 14:22:42 pppd[536]: sent [LCP ConfReq id=0x1 <asyncmap 0x0> <magic 0x2e0f4591> <pcomp> <accomp>]
<7>May 20 14:22:45 last message repeated 1 time(s)
<7>May 20 14:22:45 pppd[536]: rcvd [LCP ConfReq id=0x69 <asyncmap 0x0> <auth chap MD5> <magic 0x21d7fe1f> <pcomp> <accomp>]
<7>May 20 14:22:45 pppd[536]: lcp_reqci: returning CONFACK.
<7>May 20 14:22:45 pppd[536]: sent [LCP ConfAck id=0x69 <asyncmap 0x0> <auth chap MD5> <magic 0x21d7fe1f> <pcomp> <accomp>]
<7>May 20 14:22:45 pppd[536]: rcvd [LCP ConfAck id=0x1 <asyncmap 0x0> <magic 0x2e0f4591> <pcomp> <accomp>]
<7>May 20 14:22:45 pppd[536]: sent [LCP EchoReq id=0x0 magic=0x2e0f4591]
<7>May 20 14:22:45 pppd[536]: rcvd [LCP ConfReq id=0x6a <asyncmap 0x0> <auth chap MD5> <magic 0x21d7fe1f> <pcomp> <accomp>]
<7>May 20 14:22:45 pppd[536]: sent [LCP ConfReq id=0x2 <asyncmap 0x0> <magic 0x3e9f050f> <pcomp> <accomp>]
<7>May 20 14:22:45 pppd[536]: lcp_reqci: returning CONFACK.
<7>May 20 14:22:45 pppd[536]: sent [LCP ConfAck id=0x6a <asyncmap 0x0> <auth chap MD5> <magic 0x21d7fe1f> <pcomp> <accomp>]
<7>May 20 14:22:45 pppd[536]: rcvd [LCP ConfReq id=0x6b <asyncmap 0x0> <auth chap MD5> <magic 0x21d7fe1f> <pcomp> <accomp>]
<7>May 20 14:22:45 pppd[536]: lcp_reqci: returning CONFACK.
<7>May 20 14:22:45 pppd[536]: sent [LCP ConfAck id=0x6b <asyncmap 0x0> <auth chap MD5> <magic 0x21d7fe1f> <pcomp> <accomp>]
<7>May 20 14:22:45 pppd[536]: rcvd [LCP ConfReq id=0x6c <asyncmap 0x0> <auth chap MD5> <magic 0x21d7fe1f> <pcomp> <accomp>]
<7>May 20 14:22:45 pppd[536]: lcp_reqci: returning CONFACK.
<7>May 20 14:22:45 pppd[536]: sent [LCP ConfAck id=0x6c <asyncmap 0x0> <auth chap MD5> <magic 0x21d7fe1f> <pcomp> <accomp>]
<7>May 20 14:22:45 pppd[536]: rcvd [LCP ConfAck id=0x1 <asyncmap 0x0> <magic 0x2e0f4591> <pcomp> <accomp>]
<7>May 20 14:22:45 pppd[536]: rcvd [LCP ConfAck id=0x2 <asyncmap 0x0> <magic 0x3e9f050f> <pcomp> <accomp>]
<7>May 20 14:22:45 pppd[536]: sent [LCP EchoReq id=0x0 magic=0x3e9f050f]
<7>May 20 14:23:45 pppd[536]: sent [LCP EchoReq id=0x1 magic=0x3e9f050f]
<7>May 20 14:23:45 pppd[536]: rcvd [LCP DiscReq id=0x6d magic=0x21d7fe1f]
<7>May 20 14:24:45 pppd[536]: sent [LCP EchoReq id=0x2 magic=0x3e9f050f]
<6>May 20 14:25:45 pppd[536]: No response to 3 echo-requests
<5>May 20 14:25:45 pppd[536]: Serial link appears to be disconnected.
<7>May 20 14:25:45 pppd[536]: sent [LCP TermReq id=0x3 "Peer not responding"]
<7>May 20 14:25:45 pppd[536]: rcvd [CHAP Challenge id=0x1 <65eddeffbe55d8c4b79039c1da9bd5db>, name = "UMTS_CHAP_SRVR"]
<7>May 20 14:25:48 pppd[536]: sent [LCP TermReq id=0x4 "Peer not responding"]
<5>May 20 14:25:51 pppd[536]: Connection terminated.
<6>May 20 14:25:52 pppd[536]: Exit.

**Comment by enaess** [comment]
This LCP conversation is a bit strange as pppd is receiving a CONFREQ And consequently replies the request with a CONFACK, just to be replied back with a new CONFREQ with same parameters, but id is bumped up by +1. It's like the peer doesn't see our response, though it does respond with an CONFACK to the CONFREQ pppd is sending.
```
R: <7>May 20 14:22:45 pppd[536]: rcvd [LCP ConfReq id=0x69 <asyncmap 0x0> <magic 0x21d7fe1f> ]
S: <7>May 20 14:22:45 pppd[536]: sent [LCP ConfAck id=0x69 <asyncmap 0x0> <magic 0x21d7fe1f> ]
R: <7>May 20 14:22:45 pppd[536]: rcvd [LCP ConfReq id=0x6a <asyncmap 0x0> <magic 0x21d7fe1f> ]
```
Then immediately, the local pppd is starting to send LCP echo requests
```
<7>May 20 14:22:45 pppd[536]: sent [LCP EchoReq id=0x0 magic=0x2e0f4591]
... [then b/c of the repeated LCP CONFREQ/CONFACK both agrees on the next magic number: 0x3e9f050f
<7>May 20 14:22:45 pppd[536]: sent [LCP EchoReq id=0x0 magic=0x3e9f050f]
<7>May 20 14:23:45 pppd[536]: sent [LCP EchoReq id=0x1 magic=0x3e9f050f]
.. and 
<7>May 20 14:24:45 pppd[536]: sent [LCP EchoReq id=0x2 magic=0x3e9f050f]
.. then finally
<6>May 20 14:25:45 pppd[536]: No response to 3 echo-requests
<5>May 20 14:25:45 pppd[536]: Serial link appears to be disconnected.
<7>May 20 14:25:45 pppd[536]: sent [LCP TermReq id=0x3 "Peer not responding"]
... before we then receive CHAP CHALLENGE from peer, but connection is terminated.
```

The strange thing here is that the local pppd appears to be sending 3 ECHO REQ within the same second, despite echo interval is set to 60 seconds and echo-failure is set to 3 requests.

I have no way to effectively reproduce this. But likely using this over a serial port or chat can have some strange timing bug embedded.

**Comment by paulusmack** [comment]
ppp-2.3.8 is more than 20 years old now and a lot has changed since then. If this is still a problem with the current code, or even with ppp-2.4.9, then post the logs and we can look for the bug.

**Comment by davbatt** [comment]
Hi, sorry, several months have passed, I had forgotten to close the issue that I had already resolved. The problem was due to incorrect control of the hw signals, and futhermore I had to specify the remote IP address as a parameter.
Now it works correctly.
Thanks
