### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by kloczek** [ppp-project/ppp#350]
https://github.com/ppp-project/ppp/compare/ppp-2.4.9...master shows already +130 commits.
It is always better to make release with smaller batches of commits.
Please consider to make the new release soon.

**Comment by Neustradamus** [comment]
I think last PRs before the new build will be:
- https://github.com/ppp-project/ppp/pull/377
- https://github.com/ppp-project/ppp/pull/378
- https://github.com/ppp-project/ppp/pull/379

**Comment by Neustradamus** [comment]
@paulusmack: About the Debian 12 freeze deadline:
- https://release.debian.org/bookworm/freeze_policy.html

cc: @bootc.

**Comment by paulusmack** [comment]
I think we're very close to being able to do a release; it's mostly now a matter of writing some release notes to go into the README file and then creating the tarballs and putting them up.

I'd like to hear from the contributors to this release if there are any particular items that should be mentioned in the README.

@carlsonj could you check that all appears to be OK on Solaris please?

**Comment by Neustradamus** [comment]
@enaess, @jjkeijser, @jkroonza, @bootc, @rfc1036, @yarda, @dfskoll: ^

@paulusmack: Can you look:
- https://github.com/ppp-project/ppp/pull/386
- https://github.com/ppp-project/ppp/issues/387

**Comment by yarda** [comment]
> @enaess, @jjkeijser, @jkroonza, @bootc, @rfc1036, @yarda, @dfskoll: ^
> 
LGTM, thanks. I have no particular requirements regarding the release notes.

**Comment by enaess** [comment]
@thesamesam how does current PPP/master compile on Gentoo with the latest GCC (as you found with sstp-client)?

**Comment by thesamesam** [comment]
> @thesamesam how does current PPP/master compile on Gentoo with the latest GCC (as you found with sstp-client)?

Cheers for the ping! Let me have a look either tomorrow or day after.

**Comment by jkroonza** [comment]
```
jkroon@plastiekpoot ~/projects/ppp (master) $ ./configure
...
ppp version 2.5.0
    Prefix...............: /usr/local
    Runtime Dir..........: ${localstatedir}/run/pppd
    Logfile Dir..........: ${prefix}/var/log/ppp
    Plugin Dir...........: ${exec_prefix}/lib/pppd/2.5.0
    With OpenSSL.........: yes
    With libatm..........: no
    With libpam..........: yes
    With libpcap.........: yes
    With libsrp..........: no
    C Compiler...........: gcc -g -O2
    Linker...............: /usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64  

Features enabled
    Microsoft Extensions.: yes
    Multilink............: no
    Plugins..............: yes
    CBCP.................: no
    IPV6CP...............: yes
    EAP-TLS..............: yes
    PEAP.................: yes
    systemd notifications: no
jkroon@plastiekpoot ~/projects/ppp (master) $ make -j16
...
make[2]: Leaving directory '/home/jkroon/projects/ppp/pppd/plugins'
make[1]: Leaving directory '/home/jkroon/projects/ppp/pppd/plugins'
make[1]: Entering directory '/home/jkroon/projects/ppp'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/jkroon/projects/ppp'
jkroon@plastiekpoot ~/projects/ppp (master) $ 
```

@thesamesam is there anything else you'd like to test specifically?  I've run pppoe-server with this as well on my test host, and I'm fairly certain if there are problems I'll be able (and more than willing to ... time permitting which since you're pinging me on other bugs know is fairly limited).

**Comment by thesamesam** [comment]
@jkroonza The main task is to just port the ebuild to autotools and see if everything works okay, or if we're missing some way to do something we used to do in the new setup. Ideally someone who uses ppp could do that (you? 😀) at least for a first pass, then I could tidy it up if needed.

**Comment by jkroonza** [comment]
I can build it standalone from master branch, so if a release is made I'm sure I'll be able to port the ebuild, hopefully including most patches that wasn't merged upstream (and with permission from original authors ideally submit them here too).  If any individual patch gets stuck we should probably also evaluate if it's a required patch, ie, reach out or block it temporarily with a news item.  That's Gentoo problems though, not ppp, and IMHO shouldn't be a cause for blocking a new release.  If we need assistance from ppp I'm sure we will be able to motivate a 2.5.1 release.

**Comment by paulusmack** [comment]
I think the tree is ready for release. Last call for anything that really needs to be fixed before 2.5.0...

**Comment by paulusmack** [comment]
2.5.0 is out there now.

**Comment by Neustradamus** [comment]
Dear all,

@paulusmack will prepare a 2.5.1 release build and ask some questions:
- https://github.com/ppp-project/ppp/issues/460

Can you look it?

Thanks in advance.

**Comment by Neustradamus** [comment]
PPP 2.5.1 has been released (2024-09-18)
- https://github.com/ppp-project/ppp/releases/tag/ppp-2.5.1

**Comment by Neustradamus** [comment]
Dear all,

@paulusmack has planned a new build in few days, you have not patches?

@bootc, @rfc1036: What is the latest date to have a new PPP version (2.5.2) in Debian Testing before Debian 13 freeze?

**Comment by dfskoll** [comment]
Are any patches required?

**Comment by jkroonza** [comment]
> Are any patches required?

Highly doubt it.  No functional changes, mostly relatively minor fixes, and one change to actually expose functionality rp-pppoe already implements to the ppp user scripts.

**Comment by Neustradamus** [comment]
PPP 2.5.2 has been released (2024-12-31)
- https://github.com/ppp-project/ppp/releases/tag/v2.5.2
