### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [ppp-project/ppp#353]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@un1c0rn-the-pwnie) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by paulusmack** [comment]
I added a SECURITY.md containing my email address and the key fingerprint to use for encrypting email to me. I'll flesh it out more once I know better what's needed.

**Comment by Neustradamus** [comment]
@paulusmack: Can be closed?
- https://github.com/ppp-project/ppp/commit/a6622771e2dc03a2682c86c4bcf6bf6ae9e85df7

**Comment by JamieSlome** [comment]
Just for reference, the reported security issue can be found here:
