### ISSUE TITLE
ipv6_choose_hook not present?

### ISSUE THREAD

**Issue by gr4yg00s3** [ppp-project/ppp#363]
This is more of a question/discussion than an issue. I see that when the `ipv6_up/down_hook` were added, unlike the `ip_choose_hook`, an `ipv6_choose_hook` was not added. I had a couple of questions about this, 

1. Was there a specific reason for this? 
2. Is there a plan for adding this `ipv6_choose_hook`?

**Comment by enaess** [comment]
@pali - You know the answer to this one?

**Comment by pali** [comment]
I did not know that there is such `ip_choose_hook` hook. What it this hook doing? Or better question for which thing are you using it? Or even better question, what functionality is missing in IPv6 context which you want to use? If there is some missing IPv6 functionality which makes sense and there are requests for it we could think about implementing it. But really the first thing is needed to know what is missing, how it should be used and who needs it.

**Comment by gr4yg00s3** [comment]
I was able to find out about this. So firstly, `ip_choose_hook` exists probably to allow for a user to be able to write their own IP address assigning plugin. The reason why there is no IPv6 version of  this is because according to the RFC for [IPv6 over PPP](https://www.rfc-editor.org/rfc/rfc5072.html#section-4.1) there is only one configuration option as part of the IPV6CP negotiation, that is the `Interface Identifier` unlike [IP over PPP](https://www.rfc-editor.org/rfc/rfc1332.html#section-3.3) which allows an `IP Address` being pushed. 

I believe I will just have to use regular RAs to configure a global unicast address on the client.

 ```
  The negotiated interface identifier is used by the local end of the
   PPP link to autoconfigure an IPv6 link-local unicast address for the
   PPP interface.  However, it SHOULD NOT be assumed that the same
   interface identifier is used in configuring global unicast addresses
   for the PPP interface using IPv6 stateless address autoconfiguration
   [3].  The PPP peer MAY generate one or more interface identifiers,
   for instance, using a method described in [8], to autoconfigure one
   or more global unicast addresses.

   As long as the interface identifier is negotiated in the IPV6CP phase
   of the PPP connection setup, it is redundant to perform duplicate
   address detection (DAD) as a part of the IPv6 Stateless Address
   Autoconfiguration protocol [3] on the IPv6 link-local address
   generated by the PPP peer.  It may also be redundant to perform DAD
   on any global unicast addresses configured (using an interface
   identifier that is either negotiated during IPV6CP or generated, for
   instance, as per [8]) for the interface as part of the IPv6 Stateless
   Address Autoconfiguration protocol [3] provided that the following
   two conditions are met:

      1) The prefixes advertised through the Router Advertisement
         messages by the access router terminating the PPP link are
         exclusive to the PPP link.

      2) The access router terminating the PPP link does not
         autoconfigure any IPv6 global unicast addresses from the
         prefixes that it advertises.

   Therefore, it is RECOMMENDED that for PPP links with the IPV6CP
   interface-identifier option enabled and satisfying the aforementioned
   two conditions, the default value of the DupAddrDetectTransmits
   autoconfiguration variable [3] is set to zero by the system
   management.  3GPP2 networks are an example of a technology that uses
   PPP to enable a host to obtain an IPv6 global unicast address and
   satisfies the aforementioned two conditions [10].  3GPP networks are
   another example ([11] [13]).

```

**Comment by pali** [comment]
`Interface Identifier` in IPv6CP is used for constructing IPv6 Link-Local address (as it is written in that RFC quote). So pppd for ipv6 assigns also IPv6 address (just it is link-local).

But my question reminds, for what purpose you need or use that ip_choose_hook (or its IPv6 equivalent)?

**Comment by gr4yg00s3** [comment]
I've written a plugin where I use the `ip_choose_hook`  to push an IP address I've selected for a requesting client in the IPCP negotiations. I was looking to write a similar plugin for push an IPv6 global unicast address and presumed IPV6CP to have the ability to push an IPv6 address as part of the IPV6CP negotiations. But according to the RFC that's not possible anyway. So my question/requirement is rendered moot. And I'll have to rely on RAs for configuring a global unicast address for the requesting client.

**Comment by pali** [comment]
What you can do in pppd to just "log" IPv6 link-local address, not IPv6 global unicast address as you already figured out.

When you are using stateless RA-based IPv6 address configuration then it is client who decide which address would use (and not RA software on router) and whole address selection is on the client, there is even no acknowledgement from server/RA.

If you wan to have IPv6 address assignment for ppp clients under your control, then you have to use DHCPv6 (in statefull mode).

**Comment by gr4yg00s3** [comment]
Yup, I took a bit of time figuring that out. I hadn't read the IPv6 over PPP RFC. Thanks for replying though 👍
