### ISSUE TITLE
Radius Change of Authorization support with pppd

### ISSUE THREAD

**Issue by kaizoku-o** [ppp-project/ppp#369]
Hi, 
Is there any existing support for Radius CoA with pppd?

Ref: https://datatracker.ietf.org/doc/html/rfc5176

**Comment by jkroonza** [comment]
@kaizoku-o not from within pppd, nor do I think that's practical.  So some hints on how to achieve this:

use freeradius on the same node as what you're running pppd on.

Have pppd use localhost as client.

Set up COA on freeradius, and have that execute a script that's capable of taking the attributes to kill the right pppd process.

This also gives you an opportunity to modify radius requests/responses (both for auth and acct) inbetween pppd generating them and being transmitted to your primary radius server (useful to inject additional attributes if desired, eg, Delegated-IPv6-Prefix).

**Comment by Neustradamus** [comment]
@enaess: Have you seen this ticket?

**Comment by jkroonza** [comment]
@Neustradamus I don't think this is a ppp issue.  My *personal* recommendation for people:

run freeradius on the local node and use that to proxy requests from ppp to actual upstream, you can then also use that to utilize it's CoA support to action the relevant (we use freeradius to basically deal with the "is this a legit CoA", and typically end up passing that to a script that just sends a signal to the appropriate pppd instance).  Honestly, I really don't see how pppd can be expected to handle the CoA request, and I think this should be treated as out of scope.

**Comment by paulusmack** [comment]
Closing this based on @jkroonza's comment that this isn't really a pppd issue.
