### ISSUE TITLE
coverity scan

### ISSUE THREAD

**Issue by chipitsine** [ppp-project/ppp#394]
Hello, @paulusmack , @enaess 

I've prepared coverity scan project and ran first build
https://scan.coverity.com/projects/pppd

feel free to request access, I'll approve it

there are things to review before 2.5.0

![image](https://user-images.githubusercontent.com/2217296/219590132-9ee8237c-ce0a-4267-abcd-4c393dad60d7.png)

**Comment by enaess** [comment]
While fixing some of these make sense. It probably would make more sense to add them to a CI build on GitHub / Master branch / weekly schedule?

It maybe enable on coverity branch, which follows master, but only builds when you copy all of master into that coverity branch to check?

**Comment by chipitsine** [comment]
I would stay with weekly schedule for master branch

**Comment by chipitsine** [comment]
I ran scan using the following pipeline: https://github.com/chipitsine/ppp/blob/ab16287327dea92339cd33d90821207b1caee864/.github/workflows/coverity.yml

I tried to rewrite it using [non travis guide](https://www.synopsys.com/blogs/software-security/integrating-coverity-scan-with-gitlab-ci/), it did not work so far: https://github.com/chipitsine/ppp/blob/master/.github/workflows/coverity.yml

**Comment by chipitsine** [comment]
also, I noticed that pppd was built with some features/libs disabled

```
ppp version 2.5.0
...
    With libpam..........: no
...
    With libsrp..........: no
...

Features enabled
...
    CBCP.................: no
...
```


I'll try to enable them to see whether build coverage will increase or not

**Comment by enaess** [comment]
Don't bother with the libsrp, also the cbcp protocol isn't frequently used. You could install libatm-dev, the it would exclude a bunch of the ATM code in the plugins. Then enable multilink would probably be good
