### ISSUE TITLE
ppp.h doesn't work without HAVE_STD..._H

### ISSUE THREAD

**Issue by yu-re-ka** [ppp-project/ppp#402]
[This change](https://github.com/ppp-project/ppp/commit/ba7f7e053daae846a54a1d08d3d133a5f1266ace) might break projects that include pppd.h, but without having the appropriate HAVE_STD..._H defines from their build system.

For instance, networkmanager does not build:

```
In file included from ../src/core/ppp/nm-pppd-plugin.c:10:
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:162:5: error: unknown type name ‘uint64_t’
  162 |     uint64_t            bytes_in;
      |     ^~~~~~~~
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:163:5: error: unknown type name ‘uint64_t’
  163 |     uint64_t            bytes_out;
      |     ^~~~~~~~
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:205:5: error: unknown type name ‘bool’
  205 |     bool enabled_flag;
      |     ^~~~
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:245:34: error: unknown type name ‘uint32_t’
  245 |         void (*send_config)(int, uint32_t, int, int);
      |                                  ^~~~~~~~
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:67:1: note: ‘uint32_t’ is defined in header ‘<stdint.h>’; did you forget to ‘#include <stdint.h>’?
   66 | #include "pppdconf.h"
  +++ |+#include <stdint.h>
   67 | 
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:247:34: error: unknown type name ‘uint32_t’
  247 |         void (*recv_config)(int, uint32_t, int, int);
      |                                  ^~~~~~~~
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:247:34: note: ‘uint32_t’ is defined in header ‘<stdint.h>’; did you forget to ‘#include <stdint.h>’?
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:262:1: error: unknown type name ‘bool’
  262 | bool debug_on();
      | ^~~~
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:67:1: note: ‘bool’ is defined in header ‘<stdbool.h>’; did you forget to ‘#include <stdbool.h>’?
   66 | #include "pppdconf.h"
  +++ |+#include <stdbool.h>
   67 | 
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:268:36: error: unknown type name ‘va_list’
  268 | int vslprintf(char *, int, char *, va_list);
      |                                    ^~~~~~~
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:67:1: note: ‘va_list’ is defined in header ‘<stdarg.h>’; did you forget to ‘#include <stdarg.h>’?
   66 | #include "pppdconf.h"
  +++ |+#include <stdarg.h>
   67 | 
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:271:1: error: unknown type name ‘size_t’
  271 | size_t strlcpy(char *, const char *, size_t);
      | ^~~~~~
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:67:1: note: ‘size_t’ is defined in header ‘<stddef.h>’; did you forget to ‘#include <stddef.h>’?
   66 | #include "pppdconf.h"
  +++ |+#include <stddef.h>
   67 | 
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:271:38: error: unknown type name ‘size_t’
  271 | size_t strlcpy(char *, const char *, size_t);
      |                                      ^~~~~~
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:271:38: note: ‘size_t’ is defined in header ‘<stddef.h>’; did you forget to ‘#include <stddef.h>’?
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:274:1: error: unknown type name ‘size_t’
  274 | size_t strlcat(char *, const char *, size_t);
      | ^~~~~~
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:274:1: note: ‘size_t’ is defined in header ‘<stddef.h>’; did you forget to ‘#include <stddef.h>’?
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:274:38: error: unknown type name ‘size_t’
  274 | size_t strlcat(char *, const char *, size_t);
      |                                      ^~~~~~
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:274:38: note: ‘size_t’ is defined in header ‘<stddef.h>’; did you forget to ‘#include <stddef.h>’?
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:335:1: error: unknown type name ‘bool’
  335 | bool ppp_get_link_stats(ppp_link_stats_st *stats);
      | ^~~~
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:335:1: note: ‘bool’ is defined in header ‘<stdbool.h>’; did you forget to ‘#include <stdbool.h>’?
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:361:1: error: unknown type name ‘pid_t’
  361 | pid_t ppp_safe_fork(int, int, int);
      | ^~~~~
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:371:1: error: unknown type name ‘bool’
  371 | bool ppp_using_pty();
      | ^~~~
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:371:1: note: ‘bool’ is defined in header ‘<stdbool.h>’; did you forget to ‘#include <stdbool.h>’?
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:376:1: error: unknown type name ‘bool’
  376 | bool ppp_sync_serial();
      | ^~~~
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:376:1: note: ‘bool’ is defined in header ‘<stdbool.h>’; did you forget to ‘#include <stdbool.h>’?
/nix/store/r9c8wbn97wma9bb8w84y6l14j3203mrb-ppp-2.5.0/include/pppd/pppd.h:381:1: error: unknown type name ‘bool’
  381 | bool ppp_get_modem();
      | ^~~~

**Comment by Neustradamus** [comment]
@enaess: ^

**Comment by enaess** [comment]
@yu-re-ka Do you have a suggestion on how this should be fixed? Partially, I am not sure I fully understand network-manager's requirement (or insistence on defining bool, some C89 vs C90 thing?).

I ran astray with something similar in the network-manager-sstp|pptp|l2tp projects (have a PR ready for network-manager-pptp by tonight), and change was already put into network-manager-sstp|l2tp projects' mainline. Had to include stdbool.h prior to nm-default.h would include a header that would define it if it didn't exist.

If a header require a system header, it should include it or you have a sore mess trying to update every reference that includes pppd.h. Are you suggesting removing the #ifdef HAVE_STDBOOL_H, or advocating for a different solution?

I was hoping to submit a PR to network-manager over the weekend and the API changes are simple, but wasn't looking forward to having to learn meson to do what I've already done with autotools. Maybe you could help there?

**Comment by yu-re-ka** [comment]
If there are patches filed upstream for network-manager and other consumers of the ppp api, this would be a fine solution for me.

However if this is an expected new requirement for consumers of the ppp api, it would be nice to document this change for 2.5.0, since the HAVE_STDBOOL_H define was previously not required.

**Comment by enaess** [comment]
I understand the situation is not ideal, and am open to changing it based on the feedback. 
pppd-2.4.9 used typedef unsigned char bool;
pppd-2.5.0, includes stdbool.h

It's unlikely, but certainly possible that a plugin is compiled with a definition of bool to be e.g. an unsigned int. A different data type than what stdbool.h defines it to be. Weird things will happen when crossing the ABI boundary between a plug-in compiled with bool of a different data type than what pppd was compiled with. 

In either case, bool is assumed to be of a data type. In pppd-2.5.0 we like to use the system definition of it. And we have not found a case where stdbool.h doesn't exist, and we do compile against a few different libc (muscl, glibc, etc). Maybe we should just remove the #ifdef HAVE_STDBOOL_H (and others in the pppd.h) and call it good?

If this won't work, e.g. Solaris breaks, then we could use a WITH_PPP_USE_STDBOOL and expose it in pppdconf.h; if pppd was compiled with stdbool.h then that is what will be used (but at least that flag is controlled by pppdconf.h and not some third party project's configure.

If we simply removed the HAVE_STDBOOL_H declaration, would that yield a solution for you?

**Comment by enaess** [comment]
@yu-re-ka You should be able to verify this fixed and close the issue.

**Comment by yu-re-ka** [comment]
Can confirm this specific compile error is fixed on master. I assume patches to update the networkmanager plugin to work with 2.5.0 will follow soon enough. Thank you!

**Comment by enaess** [comment]
@yu-re-ka Merge request created, but has some CI/CD issues with not being able to build using meson.

https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/merge_requests/1558
