### ISSUE TITLE
pppoe on master after commit ba7f7e053d is said to be broken

### ISSUE THREAD

**Issue by enaess** [ppp-project/ppp#403]
[This change ](https://github.com/ppp-project/ppp/commit/ba7f7e053daae846a54a1d08d3d133a5f1266ace) is said to break pppoe connections (see comments at the bottom by @wongsyrone)

I am filing this issue to track it here as an issue vs. in a comment on a change. Hope @wongsyrone is able to provide details here to help resolve the issue she was having. 

Also, @jkroonza I believe pppoe was working for both of us when the change was comitted.

**Comment by wongsyrone** [comment]
@enaess Please check this commit, it fixes the bug I commented.

https://github.com/wongsyrone/lede-1/commit/e1b71e92c6b0ee0fee12eb2e5fe768877e76560c

**Comment by enaess** [comment]
This is fixed in my PR to address Coverity issues. 

https://github.com/ppp-project/ppp/pull/397/commits/6889e827c5aa89c7f010e54052f2fc7907907de4

**Comment by wongsyrone** [comment]
Thanks. It makes sense.
