### ISSUE TITLE
RADIUS: Can't read config file /etc/radiusclient/radiusclient.conf

### ISSUE THREAD

**Issue by developerispbg** [ppp-project/ppp#413]
Hi,
Sorry for My English, it's not My native language.

In DEBIAN 11 Linux with, I noticed these messages in /var/daemon.log:

RADIUS: Can't read config file /etc/radiusclient/radiusclient.conf

The problem is in pppd/plugins/radius/config.c file.

In function:
int rc_read_config(char *filename)
between rows 236 to 260 we have:
`         switch (option->type) {`
`		       case OT_STR:`
`				 if (set_option_str(filename, line, option, p) < 0)`
`					fclose(configfd);`
`					return (-1);`
`				break;`
`			case OT_INT:`
`				 if (set_option_int(filename, line, option, p) < 0)`
`					fclose(configfd);`
`					return (-1);`
`				break;`
`			case OT_SRV:`
`				 if (set_option_srv(filename, line, option, p) < 0)`
`					fclose(configfd);`
`					return (-1);`
`				break;`
`			case OT_AUO:`
`				 if (set_option_auo(filename, line, option, p) < 0)`
`					fclose(configfd);`
`					return (-1);`
`				break;`
`			default:`
`				fatal("rc_read_config: impossible case branch!");`
`				abort();`
`		}`

It must be:
`        switch (option->type) {`
`			case OT_STR:`
`				 if (set_option_str(filename, line, option, p) < 0) {`
`					fclose(configfd);`
`					return (-1);`
`                 }`
`				break;`
`			case OT_INT:`
`				 if (set_option_int(filename, line, option, p) < 0) {`
`					fclose(configfd);`
`					return (-1);`
`                 }`
`				break;`
`			case OT_SRV:`
`				 if (set_option_srv(filename, line, option, p) < 0) {`
`					fclose(configfd);`
`					return (-1);`
`                 }`
`				break;`
`			case OT_AUO:`
`				 if (set_option_auo(filename, line, option, p) < 0) {`
`					fclose(configfd);`
`					return (-1);`
`                 }`
`				break;`
`			default:`
`				fatal("rc_read_config: impossible case branch!");`
`				abort();`
`		}`

with out curly braces operator: return(-1) is executed immediately after first iteration
and config file is not reading never.
I hope this post will save someone time.

**Comment by chipitsine** [comment]
do you wish to open a pull request ?

**Comment by developerispbg** [comment]
My time is limit and I am new in github.
Some suggest?

**Comment by enaess** [comment]
Do we know what config options has been passed to configure? If --sysconfdir=/etc is there still a problem resolving this directory?

**Comment by developerispbg** [comment]
Config options are OK. We work with pppd many years(>10) and configuring linux and pppd for as is a routine task.
The problem is exactly what is in post. Source in original file is with wrong syntax(python like).
In C/C++ syntax for block of operators is different {}.
After making fixing, all work fine.

**Comment by enaess** [comment]
Sorry, didn't see the proposed patch .. should be simple enough to commit.

**Comment by Neustradamus** [comment]
@enaess: Look here: https://github.com/ppp-project/ppp/issues/413#issue-1670578032

**Comment by Neustradamus** [comment]
@developerispbg: It has been solved with the @enaess PR:
- https://github.com/ppp-project/ppp/pull/417

It can be closed?
