### ISSUE TITLE
lock directory moved in ppp-2.5.0

### ISSUE THREAD

**Issue by floppym** [ppp-project/ppp#419]
With ppp-2.4.9, serial device lock files were always created in `/var/lock`.

Since 66a8c74c3f73d7480a09923a225b56b8829ae790, the lock files get created in `PPP_PATH_VARRUN "/lock"`, which evaluates to a value like `/var/run/pppd/lock` or `/run/pppd/lock` depending on the value of `runstatedir` passed to configure.

Is this change of location intentional? There are other programs that use serial ports that expect the lock files to be in /var/lock.

cc @enaess

**Comment by paulusmack** [comment]
It wasn't intentional. I suppose some people didn't realize that the lock file is not intended to be private to pppd and other people weren't sufficiently vigilant.

What do distros do these days about coordinating serial port access between different programs? Do modern distros even know what serial ports are? :)

**Comment by floppym** [comment]
On Gentoo at least, /var/lock is a symlink to /run/lock, for compatibility with "legacy" applications.

I would guess this is the case on most systemd-based distros. When sysv compatibility is enabled, systemd installs a tmpfiles drop-in that creates the /run/lock directory and the /var/lock symlink.

https://github.com/systemd/systemd/blob/v253/tmpfiles.d/legacy.conf.in#L13-L14

A couple of alternatives on Linux:

1. Use `ioctl(2)` with `TIOCEXCL` to enable exclusive mode on the tty device, and `TIOCGEXCL` to respect it as root.
2. Use advisory locks on the tty device via `flock(2)`.

**Comment by enaess** [comment]
Q: Looks like the default value for runtime directory was set to /var/run/pppd, this seems to only manage where pppd2.tdb and the lock directory. Would you be able to specify `--with-runtime-dir=/var/run` or just `/run` as the value achieve the same functionality. 

You are probably right that there something buggy in this code. The lock directory should be the same (/var/lock) but not imply the pppd run directory. In this case, only pppd2.tdb would be in this directory (/run/pppd/pppd2.tdb).

**Comment by floppym** [comment]
I think it makes more sense to keep runtime-dir set to `${runstatedir}/pppd`. That path is also used for PID files in main.c.

I am currently working around the lock directory issue with this tmpfiles.d drop-in which creates a symlink from /run/pppd/lock to /run/lock.

https://gitweb.gentoo.org/repo/gentoo.git/commit/net-dialup/ppp/files/pppd.tmpfiles?id=8f6433c8eb43faef9a1b87de9534c54c0bc4c07f

**Comment by enaess** [comment]
Okay. Still sound like something we need to fix in 2.5.1, right?

Just a heads up for debian @rfc1036

**Comment by floppym** [comment]
> Still sound like something we need to fix in 2.5.1, right?

Agreed.

**Comment by rfc1036** [comment]
Indeed, this is obviously wrong and I have reverted the change for the 2.5.0 packaging.

`PPP_PATH_LOCKDIR` on Linux must be `/var/locks/` (which I think is still the specified ABI, even if everybody that matters now makes it a symlink to `/run/locks/`), no configuration needed.

**Comment by floppym** [comment]
I assume the "s" in "/var/locks" is a typo?

**Comment by floppym** [comment]
FHS for reference: https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s09.html

**Comment by enaess** [comment]
I find it interesting that distros wants /run/locks, while the FHS states it is /var/lock. In many cases, the distro symlinks /var to /run. Do we know if FHS is out of date with the current direction the community is taking and that /run/lock is the new de-facto standard?

While it could be as simple as to set PPP_PATH_LOCKDIR to LOCALSTATEDIR /lock and let ./configure set it appropriately to /var or /run. I like to not have to expose another configure parameter for it.

**Comment by rfc1036** [comment]
The FHS is dead and buried and log superseded by the events, but I suspect that everybody formally is still using `/var/lock/` and nobody is fretting to remove the symlink. It does not really matter, distributions will adjust it if needed.

**Comment by enaess** [comment]
> The FHS is dead and buried and long superseded by the events

Uh oh? is there a different document that supersedes it, or is my gray hairs starting to show?

**Comment by floppym** [comment]
To be clear, it's /run/lock and /var/lock, NOT /run/locks and /var/locks.

**Comment by enaess** [comment]
Dully noted!

**Comment by martinetd** [comment]
FWIW one issue that's been popping up with this is that pppd does not attempt to create the directories if it's missing:
- for the rundir, the failure is just a waring and pppd continues happily: `Warning: couldn't open ppp database /run/ppp/pppd2.tdb`
- for lock though pppd fails to start (which is probably the right thing to do): `Can't create lock file /run/ppp/lock/LCK..ttyUSB3: No such file or directory`

That failure bit me in alpine where tmpfiles don't really exist (https://gitlab.alpinelinux.org/alpine/aports/-/issues/15145 - the directory is now created for the pppd service, but not when starting dynamically through e.g. NetworkManager), and it also apparently came up in openwrt given openwrt/openwrt#12848 refers to this.

Moving back to /var/lock can be supposed to be preexisting (although I guess that can be made configurable as well if some distro thinks /var/lock is obsolete), but would it make sense to check the immediate run/lock directory and try to create if if it was missing? Something as simple as `if (access(FOO_DIR, F_OK)) mkdir(FOO_DIR)` would likely work.

Happy to submit a patch for both (mkdir and changing path) if that'd help

**Comment by martinetd** [comment]
I've created two separate PRs for each issue (move back to /var/lock in #435 and try to create dir if missing in #436)
