### ISSUE TITLE
radius plugin is broken in 2.5.0, fixed by 7f89208. New release maybe?

### ISSUE THREAD

**Issue by afedorov3** [ppp-project/ppp#426]

**Comment by Neustradamus** [comment]
@paulusmack, @enaess: Have you seen this ticket?

**Comment by vuptt** [comment]
I have the same issue

**Comment by Neustradamus** [comment]
@afedorov3, @vuptt: Linked to:
- https://github.com/ppp-project/ppp/issues/460

**Comment by Neustradamus** [comment]
PPP 2.5.1 has been released (2024-09-18)
- https://github.com/ppp-project/ppp/releases/tag/ppp-2.5.1

@paulusmack, @afedorov3: Can you close this ticket?
