### ISSUE TITLE
enable_microsoft_extensions => openssl

### ISSUE THREAD

**Issue by icegood** [ppp-project/ppp#429]
Because of this line:
https://github.com/ppp-project/ppp/blob/master/pppd/crypto_ms.c#L125

ms extensions should imply openssl. Ideally, should not be depended

**Comment by Neustradamus** [comment]
@paulusmack, @enaess: Have you seen this ticket?

**Comment by enaess** [comment]
Just opened a PR for this. Yeah, remove the boogie men ...

**Comment by Neustradamus** [comment]
Thanks @icegood for this ticket and @enaess for the PR :)

I hope a comeback of @paulusmack soon!
