### ISSUE TITLE
--disable-microsoft-extensions requires --disable-peap

### ISSUE THREAD

**Issue by willyamcts** [ppp-project/ppp#433]
When disable Microsoft Extension is required disable PEAP, both are not dependent correct?

if not using `--disable-peap` the error happens in compilation:

` # ./autogen.sh --prefix=/usr/local/pppd --disable-microsoft-extensions`
```
peap.c: In function ‘peap_init’:
peap.c:522:12: error: ‘struct peap_state’ has no member named ‘chap’
  522 |         psm->chap = chap_find_digest(CHAP_MICROSOFT_V2);
      |            ^~
make[2]: *** [Makefile:1492: pppd-peap.o] Error 1
```

**Comment by Neustradamus** [comment]
@paulusmack, @enaess: Have you seen this ticket?

**Comment by enaess** [comment]
Right now, the only peap method supported is mschapv2, so yes they are sort of dependent on each other. Technically, in the future they can be disjoint...

**Comment by Neustradamus** [comment]
@enaess: Can you look it?

**Comment by Neustradamus** [comment]
@enaess: Have you progressed on it?

**Comment by enaess** [comment]
No progress, we can still ship 2.5.1 without this. People would just need to know, PEAP with CHAPv2 is the only thing that woks right now, and if you disable the CHAP extension, PEAP won't authenticate. However, in the future you could probably use PEAP-PAP or something there alike.

**Comment by paulusmack** [comment]
I should add a note to the README about this.
