### ISSUE TITLE
PPP-2.5.0 pppd need libutil.so.1?

### ISSUE THREAD

**Issue by svalensu** [ppp-project/ppp#448]
hi:
    I cross compile ppp-2.5.0 with the configuration below:
`
./configure --host=arm-linux-gnueabihf --without-openssl --without-system-ca-path --disable-openssl-engine --disable-ipv6cp --disable-eaptls --disable-peap --disable-plugins
`
  then I got pppd and download it to arm.
  when I try to run pppd, it's got a error message:
`./pppd: error while loading shared libraries: libutil.so.1: cannot open shared object file: No such file or directory`
  can anyone help me?

**Comment by Neustradamus** [comment]
@paulusmack, @enaess: Have you seen this ticket?

**Comment by paulusmack** [comment]
Sounds like your runtime system is missing a library which is available in your cross-compile build environment. Check that libutil.so.1 exists somewhere in the filesystem of the machine you're trying to run on (it should probably in /lib or /usr/lib).

**Comment by Neustradamus** [comment]
@svalensu: Have you seen the @paulusmack comment?

Thanks in advance.

**Comment by Neustradamus** [comment]
@svalensu: Have you seen the @paulusmack comment?

**Comment by paulusmack** [comment]
No feedback, closing.
