### ISSUE TITLE
Build failure of version 2.5.0 with kernel < 4.7.0

### ISSUE THREAD

**Issue by ffontaine** [ppp-project/ppp#450]
Version 2.5.0 raises the following build failure with kernel < 4.7.0:

```
sys-linux.c: In function 'get_ppp_stats_rtnetlink':
sys-linux.c:1784:29: error: field 'ifsm' has incomplete type
         struct if_stats_msg ifsm;
                             ^
```

This build failure is raised because `if_stats_msg` is unconditionally used since https://github.com/ppp-project/ppp/commit/81ad945630120cc1c27c8bb00503be42b76ff202. However, `if_stats_msg` is only available since kernel 4.7.0 and https://github.com/torvalds/linux/commit/10c9ead9f3c6bb24bddc9a96681f7d58e6623966

I would advise to add this dependency somewhere in the README and perhaps also drop those unneeded comments/defines such as https://github.com/ppp-project/ppp/blob/f5aa69baefa83c1d9316f5736c2b6521eff44a81/pppd/sys-linux.c#L135

**Comment by Neustradamus** [comment]
@paulusmack, @enaess: Have you seen this ticket?

**Comment by jkroonza** [comment]
@ffontaine could you please test and confirm PR #452?  I don't have a <4.7.0 kernel lying around to test against, but I can't see how it won't fix the problem.
