### ISSUE TITLE
openfortivpn connection is broken with ppp 2.5.0

### ISSUE THREAD

**Issue by tobip** [ppp-project/ppp#451]
I am using `openfortivpn` to connect to my workplace.
Since ppp 2.5.0 the connection stopped working, giving the output:
Peer refused to agree to his IP address.
Downgrade back to 2.4.9 works for me.

**Comment by Neustradamus** [comment]
@paulusmack, @enaess: Have you seen this ticket?

**Comment by tobip** [comment]
[pppd-log-2.5.0.log](https://github.com/ppp-project/ppp/files/12882857/pppd-log-2.5.0.log)
[pppd-log-2.4.9.log](https://github.com/ppp-project/ppp/files/12882858/pppd-log-2.4.9.log)

**Comment by DeclanMorbey** [comment]
in `/etc/ppp/options` un-comment `ipcp-accept-remote` worked for me

**Comment by Neustradamus** [comment]
@paulusmack, @enaess, @jkroonza: What do you think?

@tobip has done logs and @DeclanMorbey has done a comment.

**Comment by jkroonza** [comment]
I'm assuming the fortinet hasn't changed?

Both log files looks pretty disturbing if you ask me, I'm surprised 2.4.9 works.

**Comment by paulusmack** [comment]
In both negotiations, the peers are unable to agree on an IP address, so in both cases `ipcp-accept-remote` is the right thing to use.

The behaviour in this situation, when the peers don't agree, was changed by commit 9fe8923419a9 ("pppd: Fix enforcing peer IP address (#235)", 2021-01-26), with the comments:

```
    pppd: Fix enforcing peer IP address (#235)
    
    If peer address is specified and ipcp-accept-remote is not set then peer
    address is enforced.
    
    But there is bug in pppd which allows peer to not use supplied address when
    it reply with empty IPCP ConfReq. In this case pppd thinks that peer
    accepted its idea of remote/peer address even it is not truth.
```

So the new behaviour of failing to bring up the link when the two ends can't agree on an IP address and the `ipcp-accept-remote` option is not used is deliberate, and I think correct.

**Comment by tobip** [comment]
> I'm assuming the fortinet hasn't changed?

Yes, nothing in the network has changed.

> What's the carrier for ppp here? Are we talking l2tp? pptp? serial?

Unfortunately I don't know how to answer these questions...

**Comment by jkroonza** [comment]
> > I'm assuming the fortinet hasn't changed?
> 
> Yes, nothing in the network has changed.

"in the network" - that's quite a bold statement really.  How do you definte "the network"?  I specifically asked about fortinet.

> > What's the carrier for ppp here? Are we talking l2tp? pptp? serial?
> 
> Unfortunately I don't know how to answer these questions...

OK.  That makes things harder.

Have you tried with ipcp-accept-remote option set?

**Comment by martin-sucha** [comment]
See https://github.com/adrienverge/openfortivpn/issues/1141#issuecomment-1806834236

**Comment by paulusmack** [comment]
@tobip did the discussion referred to in the previous comment help? Is this still an issue?

**Comment by tobip** [comment]
Yes thanks, I got it.
