### ISSUE TITLE
2.5.1 release

### ISSUE THREAD

**Issue by paulusmack** [ppp-project/ppp#460]
I want to do a v2.5.1 release of PPP soon. Does anyone have any last changes before I change the version number and create a tag?

Also, does anyone have any comments or suggestions about how we announce the release?

**Comment by jkroonza** [comment]
Please can we ensure the following are addressed as well prior to release:

#453 (really a mppe secret problem with authenticating against radius)
#443 (waiting for feedback from the op, will also try to reproduce if available cycles permit)

**Comment by Bonnietwin** [comment]
The last input on this 2.5.1 release issue is now 4 months ago.

When is the expectation for version 2.5.1 to be released.

We use the ppp package in IPFire and some users are affected by the lock directory issue that was in [#419](https://github.com/ppp-project/ppp/issues/419) & [#435.](https://github.com/ppp-project/ppp/pull/435) 
Fixes for these were merged back in Oct 2023 and were expected to be in version 2.5.1

Currently IPFire users suffering from the lock directory not existing have to run a script in rc.local to create the directory at boot time.

An estimate of when 2.5.1 might be released would be good to have.

**Comment by jkroonza** [comment]
@paulusmack I'm not seeing any remaining blockers.  The byte-counter issue seems to be very specific to the op's environment, I've been unable to reproduce, the moment I can get info on how to reproduce I can make progress on that (and the op will just have to custom-patch there).  Given that we're not getting feedback on same I'm assuming it's more of an annoyance than a real problem.

**Comment by Bonnietwin** [comment]
What I did back in March 2024 for IPFire was extract a tarball of ppp based on commit e1266c7 and use that for the ppp build we use.
That gave us the changes we were looking for .
When 2.5.1 is eventually released we will then update our interim version to it.

**Comment by bashmeester** [comment]
We rebuilt the alpine linux 2.5.0 package with [radiusclient.conf commit](https://github.com/ppp-project/ppp/commit/7f89208b860ea0c41636410bfdb6a609b2772f47) applied and then pushed the raidus modules to all our systems.

**Comment by paulusmack** [comment]
It's out now.

**Comment by jkroonza** [comment]
Thank you!  Appreciate the effort.

**Comment by Neustradamus** [comment]
Thanks @paulusmack and all other contributors too!

**Comment by Neustradamus** [comment]
2024-10-16: PPP has been updated to 2.5.1 for:

ALT: @shabashaba:
- https://packages.altlinux.org/en/sisyphus/srpms/ppp/changelog/
- https://github.com/altlinux/specs/tree/sisyphus/p/ppp

Alpine: @ncopa:
- https://pkgs.alpinelinux.org/package/edge/main/x86_64/ppp
- https://github.com/alpinelinux/aports/commits/master/main/ppp

Arch: @felixonmars:
- https://archlinux.org/packages/core/x86_64/ppp/
- https://github.com/archlinux/state/blob/main/core-x86_64/ppp

Artix: @Dudemanguy:
- https://packages.artixlinux.org/packages/system/x86_64/ppp/

Chimera: @nekopsykose:
- https://pkgs.chimera-linux.org/packages?name=ppp
- https://github.com/chimera-linux/cports/tree/master/main/ppp

CRUX: @timb87:
- https://git.crux.nu/ports/opt/src/branch/3.7/ppp
- https://crux.nu/ports/crux-3.7/opt/ppp/

Debian Experimental: @bootc:
- https://salsa.debian.org/debian/ppp

Gentoo: @jkroonza and @floppym
- https://packages.gentoo.org/packages/net-dialup/ppp
- https://gitweb.gentoo.org/repo/gentoo.git/tree/net-dialup/ppp
- https://github.com/gentoo/gentoo/tree/master/net-dialup/ppp

KaOS: @demmm:
- https://kaosx.us/packages/view.php?name=core/ppp-2.5.1-1
- https://github.com/KaOSx/core/tree/master/ppp

Liguros:
- https://gitlab.com/liguros/liguros-repo/-/tree/develop/net-dialup/ppp

OpenMamba:
- https://openmamba.org/en/packages/?tag=base&pkg=ppp.source
- https://src.openmamba.org/rpms/ppp

OpenWrt: @DragonBluep and @icegood:
- https://github.com/openwrt/openwrt/pull/16605

Parabola:
- https://www.parabola.nu/packages/core/x86_64/ppp/

Side: @4fury-c3440d8:
- https://codeberg.org/side/side/src/branch/master/runtime/_base_/ppp

Slackware: @alienbob:
- http://www.slackware.com/config/ppp.php
- https://mirrors.slackware.com/slackware/slackware-current/source/n/ppp/
- https://git.slackware.nl/current/tag/?h=20240920192540

T2: @rxrbln:
- https://www.t2sde.org/packages/ppp

Thanks to all.

Others, please check it, thanks in advance.

**Comment by naortega** [comment]
Cool! Now do Manjaro, plz. :3

**Comment by jkroonza** [comment]
> Cool! Now do Manjaro, plz. :3

Speaking as major consumer of ppp, xl2tpd and pppoe-server, and ad-hoc helping with packaging ppp on Gentoo (amongst other packages).

Get the Manjaro maintainers to do the required, not the responsibility of the ppp-project to update for each and every possible distribution.  ppp-protect maintains the core software, and various distribution packagers then package this for all the relevant distributions.  To the point where I'm surprised that a full list of distributions that have updated is even listed here, that's as far as FLOSS goes very unusual, and quite impressive by @Neustradamus.

The right approach is to file a bug on the Manjaro bug tracker that ppp is out of date, and then driving it from there.

**Comment by naortega** [comment]
> > Cool! Now do Manjaro, plz. :3
> 
> Speaking as major consumer of ppp, xl2tpd and pppoe-server, and ad-hoc helping with packaging ppp on Gentoo (amongst other packages).
> 
> Get the Manjaro maintainers to do the required, not the responsibility of the ppp-project to update for each and every possible distribution. ppp-protect maintains the core software, and various distribution packagers then package this for all the relevant distributions. To the point where I'm surprised that a full list of distributions that have updated is even listed here, that's as far as FLOSS goes very unusual, and quite impressive by @Neustradamus.
> 
> The right approach is to file a bug on the Manjaro bug tracker that ppp is out of date, and then driving it from there.

You're right, I know that this is a Manjaro thing. I guess I was merely expressing my frustration with how long Manjaro is taking to update, considering that v2.5.0 is causing issues in our production environment. I know it's their problem. Currently they have it in testing, but not in stable.

Again, my apologies.

**Comment by Neustradamus** [comment]
@naortega: No problem :)
I have no contact about Manjaro team badly.
But it is currently in Manjaro Unstable and Manjaro Testing.

**Comment by Neustradamus** [comment]
Dear all,

@paulusmack has planned a new build in few days, you have not patches?

@bootc, @rfc1036: What is the latest date to have a new PPP version (2.5.2) in Debian Testing before Debian 13 freeze?

**Comment by bootc** [comment]
> @bootc, @rfc1036: What is the latest date to have a new PPP version (2.5.2) in Debian Testing before Debian 13 freeze?

No freeze has yet been announced. You can track this yourself at https://release.debian.org/testing/freeze_policy.html and there will be an announcement on our mailing lists some time ahead of any freeze. I expect ppp 2.5.2 to easily get in to Trixie at this stage, even with my customary tardiness / lazyness. 😄

**Comment by Neustradamus** [comment]
@bootc: Yes I know, every Debian version, the first step is 202X-01-12, it is soon ^^
Of course, I know about this link: https://release.debian.org/testing/freeze_policy.html.

PPP 2.5.2 already out, hope that you will not wait a long time, better to have tests...

**Comment by Neustradamus** [comment]
PPP 2.5.2 has been released (2024-12-31)
- https://github.com/ppp-project/ppp/releases/tag/v2.5.2
