### ISSUE TITLE
PPPD 2.4.9 cannot send PADT message when DISCONNECTED

### ISSUE THREAD

**Issue by KuoEuran** [ppp-project/ppp#465]
Hi,
     I found that PPPD 2.4.9 delete sendPADT.patch and add conn->discoverySocket=-1 in discovery() function, but after I recover these modifications, but it also cannot sendPADT message when disconneced.
PS: 1. it can send PADT message in PPPD 2.4.7.
      2. PADR AND PADI message successfully sent when connected to pppoe wan.

**Comment by Neustradamus** [comment]
@paulusmack, @enaess: Have you seen this ticket?

**Comment by KuoEuran** [comment]
Hi @Neustradamus ,
     Explain in more detail, discovery() function has assigned -1 to conn->discoverySocket in discovery.c, when I reboot my DUT, the program enters PPPOEDisconnectDevice function, but it can't send PADT message normally in PPPD2.4.9 though I add sendPADT function in front of if(conn->discoverySocket>=0). In this situation, because conn->discoverySocket is -1, sendPADT function will return when  conn->discoverySocket is -1, therefore, it can't send PADT is normal.
     In second experiment, I delete the code which assigned -1 to conn->discoverySocket in discovery.c, and conn->discoverySocket is 14 which makes the program enter if(conn->discoverySocket>=0) in function PPPOEDisconnectDevice. However, I discovered that it return -1 in parameter err in sendPacket() function in if.c when I reboot system or kill the pppd process. Therefore, it cannot send PADT message.
     If you have any ideas on this situation, please give me some advice or maybe we can have some discussions in google meeting, thanks.

**Comment by Neustradamus** [comment]
@paulusmack, @enaess, @jkroonza, @chipitsine: What do you think?

**Comment by paulusmack** [comment]
I don't really follow what the actual problem is. What is the situation where you want pppd to send a PADT and it doesn't?

**Comment by KuoEuran** [comment]
Hi, @paulusmack 
    Thank you for replying. When I reboot or firmware upgrade DUT which installed openwrt, or when I kill the PPPD process in background, it should send PADT but it doesn't.

**Comment by paulusmack** [comment]
I think it was commit 2b4166d02ed0 that broke this.

Please test the fixpppoe branch (or PR #470) and tell me if it fixes the problem.

**Comment by KuoEuran** [comment]
Hi @paulusmack ,
    thank you for replying, this fixpppoe branch fixes the problem.

**Comment by Neustradamus** [comment]
@KuoEuran: @paulusmack has merged today the PR :)

Can you close your issue?

**Comment by KuoEuran** [comment]
hi @

**Comment by KuoEuran** [comment]
@Neustradamus I have closed this issue, thanks.
