### ISSUE TITLE
ppp2.5.0 chap authentication failed

### ISSUE THREAD

**Issue by lxzxjchan** [ppp-project/ppp#471]
Hi,
after I upgraded ppp from 2.4.9 to 2.5.0, chap authentication failed and pppoe dial-up failed.  Judging from the packets captured through tcpdump, the response "VALUE" in the chap authentication response message seems to be unusually long and contains many 0s.
 I used chap one-way authentication. When my code works with ppp 2.4.9, everything works fine, but when it works with ppp2.5.0, the above problem occurs.
What should I check?
Thanks.

**Comment by Neustradamus** [comment]
@paulusmack, @enaess: Have you seen this ticket?

**Comment by enaess** [comment]
@lxzxjchan you able to post or email the pcap file to either myself or Paul? Are you using chap-md5 in that case?

**Comment by Neustradamus** [comment]
@lxzxjchan: Have you seen the @enaess comment to debug?

If you want to do by email, addresses are:
- https://github.com/ppp-project/ppp/blob/master/ChangeLog
- https://github.com/ppp-project/ppp/blob/master/SECURITY.md

**Comment by jkroonza** [comment]
Are you using radius by any chance?

**Comment by lxzxjchan** [comment]
Thank you for your answers. I apologize for not replying in time as I have been busy recently.
I found the cause of this problem. That's because I specified the path to openssl when compiling, so md5_init uses the version defined by openssl. So my solution is to specify not to use openssl when compiling. @paulusmack @enaess @jkroonza

**Comment by lxzxjchan** [comment]
Thank you for your answers. I apologize for not replying in time as I have been busy recently.
I found the cause of this problem. That's because I specified the path to openssl when compiling, so md5_init uses the version defined by openssl. So my solution is to specify not to use openssl when compiling. @paulusmack @enaess @jkroonza
