### ISSUE TITLE
Serial device lock file directory

### ISSUE THREAD

**Issue by vostrelt** [ppp-project/ppp#475]
Hello there,
I ran into following situation. I want the `pppd` to run with runtime directory `/var/run/ppp/` but to store serial device `lock` files in directory `/var/lock/` as it is Linux standard. I think there is no way to achieve this with current `configure` options. So i looked in the `pathnames.h` and ask myself - shouldn't the line
```
#define PPP_PATH_LOCKDIR        PPP_PATH_VARRUN  "/lock"
```
be 
```
#define PPP_PATH_LOCKDIR        LOCALSTATEDIR  "/lock"
```
?

**Comment by rfc1036** [comment]
That was a mistake and has been fixed in https://github.com/ppp-project/ppp/commit/99cbf5e269994482edaf64624be8b1c806f9587c .

**Comment by vostrelt** [comment]
OK, thanks!
