### ISSUE TITLE
Missing configure script in 2.5.0 release

### ISSUE THREAD

**Issue by vostrelt** [ppp-project/ppp#477]
Hello there,

previous releases had `configure` scripts shipped with them. I understand that starting from version 2.5.0, `automake` is used. However, wouldn't it be better to generate the `configure` scripts for the releases?

Thanks for your work, Tomáš

**Comment by paulusmack** [comment]
@enaess how do we get a pre-built configure script included in the generated tarball?

**Comment by enaess** [comment]
As a part of the release process one should run

./autogen.sh
# configure runs ...
make dist-gz


This should create the tarball that is to be released and includes the configure script.

Also, I am away from the keyboard right now, but check the generated makefile, it could be 'make dist-zip' or something like that.

**Comment by rfc1036** [comment]
Since distributions want to generate the configure script at build time and random users are not really supposed to build ppp themselves then I think that it is totally fine if they also have to run autogen.sh.

**Comment by enaess** [comment]
@rfc1036 I think requiring a package to run 'autogen.sh' brings along a bunch of extra dependencies for the package to build. 

You as a packager may see something different in practice, but I'd say most projects do not distribute the autogen.sh, it's used by developers to bootstrap the build. 

This is why I suggested just follow the intended design and omit the autogen.sh and to use configure

**Comment by Neustradamus** [comment]
What solution can be done for this ticket?

**Comment by TomasVostrel** [comment]
@Neustradamus As for me, I would prefer to have the configure script included in the release tarball. Including it by default would be consistent with previous releases and make it more convenient for users.

**Comment by vostrelt** [comment]
@Neustradamus As for me, I would prefer to have the configure script included in the release tarball. Including it by default would be consistent with previous releases and make it more convenient for users.

**Comment by paulusmack** [comment]
ppp-2.5.1 is out now, and it has the ./configure script.
