### ISSUE TITLE
automatically reconnect after modem reboot

### ISSUE THREAD

**Issue by lillian-b** [ppp-project/ppp#491]
I have a ISP provided modem connected to my linux server, with pppd running on the linux box. if I power cycle the modem, pppd does not realise it needs to reconnect, and will keep a stuck connection until I manually restart it. (the linux box and modem are connected via a switch, so the physical link does not necessarily go down.)
is there a way in pppd to get around this issue, as to not have to set up a separate watchdog process myself?

**Comment by paulusmack** [comment]
This kind of thing is what the lcp-echo-interval and lcp-echo-failure options are often used for.

**Comment by Neustradamus** [comment]
@lillian-b: Have you seen the @paulusmack comment?

**Comment by Neustradamus** [comment]
@lillian-b: Have you seen the @paulusmack comment?
