### ISSUE TITLE
make install overwrites existing configuration files

### ISSUE THREAD

**Issue by paulusmack** [ppp-project/ppp#516]
make install will currently overwrite files in `<sysconfdir>/ppp` with "sample" copies from etc.ppp (i.e., options, chap-secrets, pap-secrets, etc.). This seems like a bad idea to me. Is there some way we can tell autoconf/automake to generate Makefile code that will check for existing files and not overwrite them?

@enaess ?

**Comment by enaess** [comment]
```
sampledir = $(sysconfdir)/$(PACKAGE)
sample_DATA = \
    etc.ppp/options \
    etc.ppp/chap-secrets \
    etc.ppp/pap-secrets \
    etc.ppp/eaptls-server \
    etc.ppp/eaptls-client \
    etc.ppp/openssl.cnf
````

I agree, that is indeed a bad idea. Typically, one would install examples like /etc/ppp/options.example and it would be the packager's responsibility to setting up the /etc/ppp/options file according to the distribution's need. Most importantly, when we do run the `make install` command, it shouldn't overwrite existing configuration files (could overwrite the examples).

**Comment by paulusmack** [comment]
> I agree, that is indeed a bad idea. Typically, one would install examples like /etc/ppp/options.example and it would be the packager's responsibility to setting up the /etc/ppp/options file according to the distribution's need. Most importantly, when we do run the `make install` command, it shouldn't overwrite existing configuration files (could overwrite the examples).

So the question is, how do you get autoconf/automake to generate a Makefile rule to do that (i.e. not overwrite an existing file)? I had a look in the documentation for both autoconf and automake and couldn't see anything relevant.

Is the best we can do simply putting ".example" on the end of the names of all the files in etc.ppp?

**Comment by enaess** [comment]
Glancing over the documentation, I think the way to do this would be to rename the files in git to add the .example suffix, and then install that.

Package maintainers may ignore these files and remove them from the distribution at their own preference, and provide a default config based on the sample. 

Some of these sample files may even be installed under /use/share/ppp/docs or something similar instead of /etc/ppp 

Since they already are installed under /etc/ppp, maybe leave them there. It's mostly for us developers to set the right config and muck with it..

@rfc1036 @yarda any opinion from you?

**Comment by rfc1036** [comment]
Are people actually installing ppp using make install on real systems? Anyway, it does not matter for Debian.

**Comment by floppym** [comment]
Yeah, as a distro packager this really doesn't matter at all. The package manager will automatically prevent the config files from being overwritten without notifying the use.

**Comment by enaess** [comment]
@paulusmack so basically, `make install` is really a developer centric option anyways. Most people are going to use a .deb or .rpm to install the software so I think we are free to do whatever you think is necessary.
