### ISSUE TITLE
Configuring with --enable-microsoft-extensions=no breaks the compile

### ISSUE THREAD

**Issue by paulusmack** [ppp-project/ppp#523]
After configuring with `--enable-microsoft-extensions=no`, running make gives:

```
  CC       pppd-peap.o
peap.c: In function ‘peap_init’:
peap.c:522:12: error: ‘struct peap_state’ has no member named ‘chap’
  522 |         psm->chap = chap_find_digest(CHAP_MICROSOFT_V2);
      |            ^~
make[2]: *** [Makefile:1520: pppd-peap.o] Error 1
```

@enaess ?

**Comment by Neustradamus** [comment]
@enaess: Have you seen this @paulusmack ticket?

**Comment by Neustradamus** [comment]
@enaess: Have you seen this @paulusmack ticket?

**Comment by enaess** [comment]
If you disable Microsoft extensions then you might as well disable peap in the configuration too. Mschap is the only working peap method at this point.

**Comment by paulusmack** [comment]
So then we should make peap depend on ms-extensions at the configure stage...

**Comment by enaess** [comment]
@paulusmack for the time being, I think that would be appropriate. There might be a time in the future someone would add e.g. PEAP-SHA1 or something similar, which should allow configuring PEAP with whatever it supports. But since MsChapv2 is the only supported PEAP mechanisms now, then yes ...

**Comment by Neustradamus** [comment]
Hope it can be added before a 2.5.1.1 or 2.5.2 release :)
