### ISSUE TITLE
2.5.1 - Build failure compiling without openssl support

### ISSUE THREAD

**Issue by rascheel** [ppp-project/ppp#534]
There is a build error when compiling without openssl support:

Error Snippet:
../../ppp-2.5.1/pppd/crypto.c: In function 'PPP_crypto_deinit':
../../ppp-2.5.1/pppd/crypto.c:240:5: warning: implicit declaration of function 'ERR_free_strings' [-Wimplicit-function-declaration]
  240 |     ERR_free_strings();
      |     ^~~~~~~~~~~~~~~~
pppd/crypto.c:240: undefined reference to `ERR_free_strings'

I'm building this as part of a yocto project for an embedded system so hard to provide the whole build trace, but the error is pretty self evident from reading the code. The ` #if OPENSSL_VERSION_NUMBER < 0x10100000L ` is evaluating as true. It should be wrapped in a `#ifdef PPP_WITH_OPENSSL` as undefined macros default to 0.

A diff for fixing that one file is below, and was the only compile error I ran into but wouldn't be surprised if there are similar errors elsewhere.

(Had to put .txt on the end of the .patch file for github to let me upload it, known issue on Linux apparently)

[0001-Fix-Openssl-defs.patch.txt](https://github.com/user-attachments/files/17781808/0001-Fix-Openssl-defs.patch.txt)

**Comment by Neustradamus** [comment]
@rascheel: @tpaukrt has done a PR few days ago:
- https://github.com/ppp-project/ppp/pull/533

@paulusmack: What do you think?

**Comment by rascheel** [comment]
Looks like @tpaukrt's PR matches up as the same changes as my .patch. Thanks Neustradamus, I searched for existing issues but didn't search existing PRs.

**Comment by paulusmack** [comment]
I just merged #533, which should fix this problem.

**Comment by Neustradamus** [comment]
@rascheel: Can you close your ticket?
