### ISSUE TITLE
Add support for PEAP?

### ISSUE THREAD

**Issue by amosshapira** [ppp-project/ppp#59]
jumpcloud.com, an 'LDAP as a Service' and 'RADIUS as a Service' provider, tells me that they only support PEAP (https://en.wikipedia.org/wiki/Protected_Extensible_Authentication_Protocol) to let me use RADIUS to authenticate VPN users.

Would it be possible to add support for this to pppd?

Thanks.

**Comment by xensystems** [comment]
Hi,
PEAP implemented by this patch https://github.com/rustylife/peap
It would be awesome if ppp devs include it in one of the future releases.

**Comment by rustylife** [comment]
https://github.com/paulusmack/ppp/pull/128

**Comment by Neustradamus** [comment]
@rustylife: Please look your PR, it has not been merged.
Thanks in advance.

**Comment by Neustradamus** [comment]
@rustylife: Please look your PR, it has not been merged...
Can you look comments...
Thanks in advance.

**Comment by enaess** [comment]
#307 Would fix this

**Comment by enaess** [comment]
We should be able to close this. @paulusmack ?

**Comment by Unb0rn** [comment]
Are there any docs on PEAP-MSCHAPv2? I'm trying to set up l2tp connection with peap, eap-mschapv2 without any cert checks, but I get:
```
pppd[2485530]: rcvd [EAP Request id=0x1 PEAP 20]
pppd[2485530]: Setting max protocol version to 0x303
pppd[2485530]: Cannot load verify locations
pppd[2485530]: Could not set CA verify locations
```
Its hard to google any data on this new feature...

**Comment by enaess** [comment]
Pppd with PEAP support isn't released yet. You would have to compile it from source (+recompile any dependent software). This isn't a easy task ...

As far as documentation goes, it should be pretty much the same options as setting up EAP-TLS. Though, you only need a CA certificate to validate the peer if I remember correctly.

**Comment by enaess** [comment]
This issue should be closed, @paulusmack ?
